### ISSUE TITLE
[BUG] System.ArgumentException \n Message : Value is an invalid value for MinimumDate (Parameter 'value')

### ISSUE THREAD

**Issue by eddyjl077** [CommunityToolkit/Maui#1381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

It only happened with DateTime.

[ObservableProperty] public DateTime _minimumDate;

later if set

MinimumDate = DateTime.Now;

Will throw exception

System.ArgumentException \n Message: Value is an invalid value for MinimumDate (Parameter 'value')

### Expected Behavior

Allow to set the Observable property of type date without throwing an exception.

### Steps To Reproduce

[ObservableProperty] public DateTime _minimumDate = DateTime.Now

### Link to public reproduction project repository

none

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS: Windows
- .NET MAUI:
```
Version : 5.3.0

### Anything else?

Exception: System.ArgumentException \n Message : Value is an invalid value for MinimumDate (Parameter 'value') \n Stack Trace:    at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 433
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 160
   at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 56
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.<PropertyChanged>b__49_0() in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 750
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action) in D:\a\_work\1\s\src\Controls\src\Core\DispatcherExtensions.cs:line 53
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.PropertyChanged(Object sender, PropertyChangedEventArgs args) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 750
   at Microsoft.Maui.Controls.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged(Object sender, PropertyChangedEventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 653
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.OnPropertyChanged(PropertyChangedEventArgs e) in /_/src/CommunityToolkit.Mvvm/ComponentModel/ObservableObject.cs:line 48

**Comment by bijington** [comment]
This looks like an issue for the MVVM toolkit and not ours. Do we have the power to transfer issues?

**Comment by brminnick** [comment]
> This looks like an issue for the MVVM toolkit and not ours. Do we have the power to transfer issues?

Agreed. 

I hoping to reproduce + confirm it before transferring it. The stack trace reads like a user-error more-so than a bug in the library. 

That being said, we do have the ability to transfer it.

**Comment by vhugogarcia** [comment]
> > This looks like an issue for the MVVM toolkit and not ours. Do we have the power to transfer issues?
> 
> Agreed.
> 
> I hoping to reproduce + confirm it before transferring it. The stack trace reads like a user-error more-so than a bug in the library.
> 
> That being said, we do have the ability to transfer it.

@brminnick I tested it locally on my project and I can confirm it is working as expected.
```csharp
[ObservableProperty]
DateTime minimumDate = DateTime.Now;
```

Then I rendered the value on the console `minimumDate.ToShortDateString()` and it worked OK: `9/5/2023`.

This does not appear to be an issue of the MVVM toolkit neither, but rather a user-error-mode.

cc: @bijington

**Comment by brminnick** [comment]
Thanks @vhugogarcia! 

Closing. Cannot reproduce.
