### ISSUE TITLE
[BUG] System.ArgumentNullException: Value cannot be null. (Parameter 'value') in ColorToColorForTextConverter.

### ISSUE THREAD

**Issue by mnowacki** [CommunityToolkit/Maui#1480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I wanted to use a converter:ColorToColorForTextConverter depending on the properties of the parent element. Parent property is bind to viewmodel property.  Like this:
```
<Frame BackgroundColor="{Binding FrameBackgroundColor}">
 <Label Text="Hello, World!" 
 TextColor="{Binding Source={RelativeSource AncestorType={x:Type Frame}}, Path=BackgroundColor, Converter={StaticResource ColorToColorForTextConverter}}"/>
</Frame>
```
When i try to show page i get: Value cannot be null. (Parameter 'value')
```
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at CommunityToolkit.Maui.Converters.ColorToColorForTextConverter.ConvertFrom(Color value, CultureInfo culture) in /_/src/CommunityToolkit.Maui/Converters/ColorToColorConverters.shared.cs:line 33
   at CommunityToolkit.Maui.Converters.BaseConverter`2[[Microsoft.Maui.Graphics.Color, Microsoft.Maui.Graphics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Graphics.Color, Microsoft.Maui.Graphics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].CommunityToolkit.Maui.Converters.ICommunityToolkitValueConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture) in /_/src/CommunityToolkit.Maui/Converters/BaseConverter.shared.cs:line 169
   at CommunityToolkit.Maui.Converters.ICommunityToolkitValueConverter.Microsoft.Maui.Controls.IValueConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture) in /_/src/CommunityToolkit.Maui/Converters/ICommunityToolkitValueConverter.shared.cs:line 52
   at Microsoft.Maui.Controls.Binding.GetSourceValue(Object value, Type targetPropertyType) in D:\a\_work\1\s\src\Controls\src\Core\Binding.cs:line 299
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 149
   at Microsoft.Maui.Controls.BindingExpression.Apply(Object sourceObject, BindableObject target, BindableProperty property) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 75
   at Microsoft.Maui.Controls.Binding.ApplyAncestorTypeBinding(BindableObject actualTarget, Element relativeSourceTarget, BindableProperty targetProperty, Element currentElement, Int32 currentLevel, List`1 chain, Object lastMatchingBctx) in D:\a\_work\1\s\src\Controls\src\Core\Binding.cs:line 212
   at Microsoft.Maui.Controls.Binding.ApplyRelativeSourceBinding(BindableObject targetObject, BindableProperty targetProperty) in D:\a\_work\1\s\src\Controls\src\Core\Binding.cs:line 166
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
   at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Java.Lang.IRunnable.cs:line 84
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
```

### Expected Behavior

I would like the converter not to throw an exception.

### Steps To Reproduce

1. Open and run solution from reproduction repository.
2. Wait for the error to occur.

### Link to public reproduction project repository

https://github.com/mnowacki/ColorToColorForTextConverterBug

### Environment

```markdown
- .NET MAUI CommunityToolkit: 6.0.0
- OS:MacOS 14.0
- .NET MAUI:7.0.310
```

**Comment by brminnick** [comment]
This is by design. `ColorToColorForTextConverter` does not accept a `null` value. 

You'll need to set the Color of the `Frame.BackgroundColor` you are binding to. 

In .NET MAUI, `Color` is a `class` and its default value (`default(Color)`) is `null`.

**Comment by brminnick** [comment]
If you'd like to suppress Exceptions from the .NET NAUI Community Toolkit converters, you can configure that in `MauiProgram.cs`:

> **Note** We do not recommend this approach 

```cs
var builder = MauiApp.CreateBuilder();
builder.UseMauiCommunityToolkit(options =>
{
    options.SetShouldSuppressExceptionsInConverters(true);
})
```



https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/options
