### ISSUE TITLE
[BUG] Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:mct:EventToCommandBehavior" in Maui Class Library

### ISSUE THREAD

**Issue by kamyaw010** [CommunityToolkit/Maui#1739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When I try to reference to something in toolkit from Maui Class Library project, the compiler throw me an error after building.
Not building success in any of my PC, same error when building.
Not works adding x:Name, x:Key no matter to the Control root or EventToCommandBehavior node

```
<ContentView xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:mct="http://schemas.microsoft.com/dotnet/2022/maui/toolkit">

    <ContentView.Resources>
        <ControlTemplate x:Key="SearchControl">
             <Entry 
                    x:Name="SearchTextBox"
                    MaximumWidthRequest="60" 
                    HorizontalTextAlignment="Start" 
                    VerticalTextAlignment="Center"
             >
                <Entry.Behaviors>
                    <mct:EventToCommandBehavior
                            x:Name="SearchEntry"
                            EventName="TextChanged"
                            Command="{Binding TextChangedCommand}"
                    />
                </Entry.Behaviors>
            </Entry>

        </ControlTemplate>
    </ContentView.Resources>
</ContentView>
```

### Verbose StackTrace

Line 48 of TaggedSearchView.xaml is the starting of **\<mct:EventToCommandBehavior \/\>** tag

```
在 TaskRun (Microsoft.Maui.Controls.Build.Tasks.XamlCTask) 期间加载的程序集: Microsoft.Maui.Controls.Build.Tasks.resources, Version=8.0.7.0, Culture=zh-Hans, PublicKeyToken=798c2ba514f889d3 (位置: C:\Users\*****\.nuget\packages\microsoft.maui.controls.build.tasks\8.0.7\buildTransitive\netstandard2.0\zh-Hans\Microsoft.Maui.Control
         s.Build.Tasks.resources.dll，MVID: c1cef779-92c3-42c5-b539-54b3afdb65ea，AssemblyLoadContext: MSBuild plugin C:\Users\*****\.nuget\packages\microsoft.maui.controls.build.tasks\8.0.7\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.Build.Tasks.dll)
                 failed.
   1:2>TaggedSearchView\TaggedSearchView.xaml(48,34): XamlC error XFC0000: Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:mct:EventToCommandBehavior". [C:\project_location::TargetFramework=net8.0-windows10.0.19041.0]
         在 TaskRun (Microsoft.Maui.Controls.Build.Tasks.XamlCTask) 期间加载的程序集: System.Diagnostics.StackTrace, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\System.Diagnostics.StackTrace.dll，MVID: 9eb8b974-5eed-40a0-9531-6f0a9589381e，AssemblyLoadCon
         text: Default)
            at Microsoft.Maui.Controls.Build.Tasks.XmlTypeExtensions.GetTypeReference(XmlType xmlType, XamlCache cache, ModuleDefinition module, IXmlLineInfo xmlInfo) in D:\a\_work\1\s\src\Controls\src\Build.Tasks\XmlTypeExtensions.cs:line 105
            at Microsoft.Maui.Controls.Build.Tasks.CreateObjectVisitor.Visit(ElementNode node, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Build.Tasks\CreateObjectVisitor.cs:line 51
            at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 159
            at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 152
            at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 154
            at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 154
            at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 154
            at Microsoft.Maui.Controls.Build.Tasks.SetPropertiesVisitor.SetDataTemplate(IElementNode parentNode, ElementNode node, ILContext parentContext, IXmlLineInfo xmlLineInfo) in D:\a\_work\1\s\src\Controls\src\Build.Tasks\SetPropertiesVisitor.cs:line 1653
            at Microsoft.Maui.Controls.Build.Tasks.SetPropertiesVisitor.Visit(ElementNode node, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Build.Tasks\SetPropertiesVisitor.cs:line 101
            at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 159
            at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 152
            at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 209
            at Microsoft.Maui.Controls.Build.Tasks.XamlCTask.TryCoreCompile(MethodDefinition initComp, ILRootNode rootnode, String xamlFilePath, TaskLoggingHelper loggingHelper, Exception& exception) in D:\a\_work\1\s\src\Controls\src\Build.Tasks\XamlCTask.cs:line 368
             Changing the module MVID
               done.
         ValidateOnly=True. Skipping writing assembly.
```

### Expected Behavior

Compile and works fine

### Steps To Reproduce

1. Create Maui project
2. Add .UseCommunityToolkit() to your builder chain in MauiProgram class
3. Create Maui class library
4. Project from step 1 should reference to project from step 3
5. In Maui Class Library create a custom page or view with any toolkit

### Link to public reproduction project repository

https://github.com/kamyaw010/YandereSuki2

### Environment

```markdown
- .NET MAUI CommunityToolkit: 7.0.1
- OS: Windows 11
- .NET MAUI: 8.0.7
```

**Comment by GeorgeLeithead** [comment]
It looks like you are adding it as a `Resource` instead of part of the page?!?

Have a look at the [Sample](https://github.com/CommunityToolkit/Maui/blob/af42a4bab7d4fe5d80f683fd60f383c47b47b241/samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/EventToCommandBehaviorPage.xaml#L24)

Also the documentation for [EventToCommandBehavior](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/event-to-command-behavior).

Otherwise, please provide a new **public reproduction project repository** as we cant see/access the one provided.
