### ISSUE TITLE
[BUG] [iOS] TouchBehaviour, Popup, and Carousel Shennanigans

### ISSUE THREAD

**Issue by asi-evin** [CommunityToolkit/Maui#1825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The Carousel loses the ability to swipe when the popup is dismissed.

### Expected Behavior

You are still able to swipe between pages of the Carousel

OR

You can't dismiss the popover and swipe the carousel at the same time.

### Steps To Reproduce

1. Run Solution in the repo on an Android device
2. Open a pop-up by pressing the "hello world" label.
3. Swip the background, which should dismiss the popup, but it also will swipe the carousel.

### Link to public reproduction project repository

https://github.com/asi-evin/PopoverCarouselBug

### Environment

```markdown
- .NET MAUI CommunityToolkit: 8.0.1
- OS: iOS 17
- .NET MAUI: 8.0.20
```

### Anything else?

I notice with the button, it's less of an issue in general, BUT I have observed the same behaviour. You can also get swipe behaviour back by pressing the label while the popover is open again, and a popup will come up before dismissing itself.

Also, if anyone can find a work-a-round, it would be a huge help; this is stopping some progress.

https://github.com/CommunityToolkit/Maui/assets/136844306/ffd7a96c-83d0-4a64-9c64-976ec88a31da

**Comment by bijington** [comment]
You might need to use the `CanBeDismissedByTappingOutsideOfPopup` property to prevent the Popup from being dismissed in this manner and add a button to the Popup that will close it.

Or consider disabling the swipe support on the CarouselView when you are showing a Popup.

**Comment by asi-evin** [comment]
Likely related to #1831

**Comment by cat0363** [comment]
@asi-evin , You can avoid this problem by implementing as below.
The code is an excerpt of the modified part.  This is a method that does not use TouchBehavior.
At least if you don't use TouchBehavior, this problem won't occur.

[MainPage.xaml]
```
                    <Label
                        x:Name="HelloWorldLabel"
                        Grid.Row="1"
                        Text="Hello, World!"
                        Style="{StaticResource Headline}"
                        SemanticProperties.HeadingLevel="Level1">
                        
                        <Label.GestureRecognizers>
                            <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped" />
                        </Label.GestureRecognizers>

                    </Label>
```

[MainPage.xaml.cs]
```
    private async void TapGestureRecognizer_Tapped(object sender, TappedEventArgs e)
    {
        if (sender is Label label)
        {
            await label.ScaleTo(0.85, 100);
            await label.ScaleTo(1.00, 100);
            this.ShowPopup(new CustomPopup { Anchor = sender as View });

        }
    }
```

If you want to adjust the animation, please change the code in MainPage.xaml.cs.
Below is the verification video.

https://github.com/user-attachments/assets/e38d3208-07e6-4c18-9b4b-28cb2d5dfc55

Is this the behavior you expect?

@bijington , When using TouchBehavior, a warning appears when debugging.
It is unclear whether this warning is related to the problem.

```
[0:] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at CommunityToolkit.Maui.Behaviors.GestureManager.SetScale(TouchBehavior sender, TouchState touchState, HoverState hoverState, TimeSpan duration, Easing easing, CancellationToken token)
   at CommunityToolkit.Maui.Behaviors.GestureManager.RunAnimationTask(TouchBehavior sender, TouchState touchState, HoverState hoverState, CancellationToken token, Nullable`1 durationMultiplier)
   at CommunityToolkit.Maui.Behaviors.GestureManager.ChangeStateAsync(TouchBehavior sender, Boolean animated, CancellationToken token)
   at CommunityToolkit.Maui.Behaviors.TouchBehavior.ForceUpdateState(CancellationToken token, Boolean animated)
```
