### ISSUE TITLE
[BUG] IsNullConverter cannont handle nullable with trigger

### ISSUE THREAD

**Issue by dhindrik** [CommunityToolkit/Maui#2075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When using a nullable type, a reference or a value type it throws and System.InvalidOperationException when using the converter with a trigger. It works with the previous version of toolkit, 9.0.1. I have tested on Windows and Android.

Exception details:
System.InvalidOperationException
  HResult=0x80131509
  Message=Non-nullable are not valid
  Source=CommunityToolkit.Maui
  StackTrace:
   at CommunityToolkit.Maui.Extensions.ValueConverterExtension.<IsValidTargetType>g__IsValidNullableValueType|2_2[TTarget](Type targetType)
   at CommunityToolkit.Maui.Extensions.ValueConverterExtension.IsValidTargetType[TTarget](Type& targetType, Boolean shouldAllowNullableValueTypes)
   at CommunityToolkit.Maui.Extensions.ValueConverterExtension.ValidateTargetType[TTarget](Type targetType, Boolean shouldAllowNullableValueTypes)
   at CommunityToolkit.Maui.Converters.BaseConverter`2.CommunityToolkit.Maui.Converters.ICommunityToolkitValueConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   at CommunityToolkit.Maui.Converters.ICommunityToolkitValueConverter.Microsoft.Maui.Controls.IValueConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   at Microsoft.Maui.Controls.Binding.GetSourceValue(Object value, Type targetPropertyType)
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindingExpression.Apply(Object sourceObject, BindableObject target, BindableProperty property, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.Binding.Apply(Object context, BindableObject bindObj, BindableProperty targetProperty, Boolean fromBindingContextChanged, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindableObject.ApplyBindings(Boolean skipBindingContext, Boolean fromBindingContextChanged)
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context)
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__89_0(BindableObject child, Object bc)
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[T](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext)
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged()
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged()
   at Microsoft.Maui.Controls.View.OnBindingContextChanged()
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context)
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__89_0(BindableObject child, Object bc)
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[T](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext)
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged()
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged()
   at Microsoft.Maui.Controls.View.OnBindingContextChanged()
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context)
   at Microsoft.Maui.Controls.TemplatedPage.SetChildInheritedBindingContext(Element child, Object context)
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__89_0(BindableObject child, Object bc)
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[T](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext)
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged()
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged()
   at Microsoft.Maui.Controls.Page.OnBindingContextChanged()
   at Microsoft.Maui.Controls.ContentPage.OnBindingContextChanged()
   at Microsoft.Maui.Controls.BindableObject.BindingContextPropertyChanged(BindableObject bindable, Object oldvalue, Object newvalue)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value)
   at Microsoft.Maui.Controls.BindableObject.set_BindingContext(Object value)
   at IsNullConverterBug.MainPage..ctor() in C:\Users\danielh\source\repos\IsNullConverterBug\IsNullConverterBug\MainPage.xaml.cs:line 11
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)

### Expected Behavior

It should not throw an exception and work like in 9.0.1.

### Steps To Reproduce

1. Clone the reproduction repo
2.  Start the app, the app will thow an exception on startup. (In our production app, it resulted in a blank page. I guess the error was handled in the background there. But I got the same exception there too.)

### Link to public reproduction project repository

https://github.com/dhindrik/IsNullConverterBug

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.2
- OS: Windows 19045.4529 and Android API 34
- .NET MAUI: Workload: 8.0.61, Nuget: 8.0.70
```

**Comment by brminnick** [comment]
Possible duplicate: https://github.com/CommunityToolkit/Maui/issues/2003

**Comment by BoungSeokKim** [comment]
me too. .net maui communitytoolit version 9.0.2.

**Comment by dhindrik** [comment]
@brminnick I wanted to try this with the latest nightly build, but this feed is not updated since 15 July, https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json. And the fix for the bug you mentioned have been merged on 24 July.  Is that feed not relevant anymore?

**Comment by DonkeyKongJr** [comment]
We can confirm the issue exists on 9.0.2, but downgrading to 9.0.1 works.

**Comment by dhindrik** [comment]
This seems to work in 9.0.3.
