### ISSUE TITLE
[BUG] [iOS] Crash on startup

### ISSUE THREAD

**Issue by Larhei** [CommunityToolkit/Maui#2158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

After adding this dependencies to  a blank new Maui App created by VS4Mac
```
	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.80" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.80" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
		<PackageReference Include="CommunityToolkit.Maui" Version="9.0.3" />
	</ItemGroup>
```

and adding UseMauiCommunityToolkit in the MauiProgram the app is crashing on my iOS 15 17.2 Simulators.

### Expected Behavior

It is not crashing.

### Steps To Reproduce

1. Checkout
2. Run

### Link to public reproduction project repository

https://github.com/Larhei/Maui-Issues/tree/main/CommunityToolkitCrash

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.3
- OS: iOS 17.2
- .NET MAUI: 8.0.80
```

### Anything else?

Unhandled Exception:
System.TypeLoadException: Could not set up parent class, due to: Invalid generic instantiation assembly:/Users/lars/Library/Developer/CoreSimulator/Devices/8A23F9D5-1BE5-4094-AEC5-712F50FEE6E5/data/Containers/Bundle/Application/98766B0A-DAAD-41A5-A8CA-72CE4010C2B1/CommunityToolkitCrash.app/Microsoft.Maui.dll type:ViewHandler`2 member:(null)
   at CommunityToolkit.Maui.AppBuilderExtensions.<>c.<UseMauiCommunityToolkit>b__0_0(IMauiHandlersCollection h)
   at Microsoft.Maui.Hosting.HandlerMauiAppBuilderExtensions.HandlerRegistration.AddRegistration(IMauiHandlersCollection builder)
   at Microsoft.Maui.Hosting.Internal.MauiHandlersFactory.CreateHandlerCollection(IEnumerable`1 registrationActions)
   at Microsoft.Maui.Hosting.Internal.MauiHandlersFactory..ctor(IEnumerable`1 registrationActions)
   at Microsoft.Maui.Hosting.HandlerMauiAppBuilderExtensions.<>c.<ConfigureMauiHandlers>b__1_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Extensions.DependencyInjection.ServiceProvider.ServiceAccessor, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].GetOrAdd(ServiceIdentifier key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IMauiHandlersFactory](IServiceProvider provider)
   at Microsoft.Maui.MauiContext.<.ctor>b__2_0()
   at System.Lazy`1[[Microsoft.Maui.IMauiHandlersFactory, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[Microsoft.Maui.IMauiHandlersFactory, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[Microsoft.Maui.IMauiHandlersFactory, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].CreateValue()
   at System.Lazy`1[[Microsoft.Maui.IMauiHandlersFactory, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Value()
   at Microsoft.Maui.MauiContext.get_Handlers()
   at Microsoft.Maui.Platform.ElementExtensions.SetHandler(INativeObject nativeElement, IElement element, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.SetApplicationHandler(IUIApplicationDelegate platformApplication, IApplication application, IMauiContext context)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at CommunityToolkitCrash.Program.Main(String[] args) in /Users/lars/workspace/Maui-Issues/CommunityToolkitCrash/CommunityToolkitCrash/Platforms/iOS/Program.cs:line 13
2024-08-28 22:56:16.938020+0200 CommunityToolkitCrash[4022:45549] Unhandled managed exception: Could not set up parent class, due to: Invalid generic instantiation assembly:/Users/lars/Library/Developer/CoreSimulator/Devices/8A23F9D5-1BE5-4094-AEC5-712F50FEE6E5/data/Containers/Bundle/Application/98766B0A-DAAD-41A5-A8CA-72CE4010C2B1/CommunityToolkitCrash.app/Microsoft.Maui.dll type:ViewHandler`2 member:(null) (System.TypeLoadException)
   at CommunityToolkit.Maui.AppBuilderExtensions.<>c.<UseMauiCommunityToolkit>b__0_0(IMauiHandlersCollection h)
   at Microsoft.Maui.Hosting.HandlerMauiAppBuilderExtensions.HandlerRegistration.AddRegistration(IMauiHandlersCollection builder)
   at Microsoft.Maui.Hosting.Internal.MauiHandlersFactory.CreateHandlerCollection(IEnumerable`1 registrationActions)
   at Microsoft.Maui.Hosting.Internal.MauiHandlersFactory..ctor(IEnumerable`1 registrationActions)
   at Microsoft.Maui.Hosting.HandlerMauiAppBuilderExtensions.<>c.<ConfigureMauiHandlers>b__1_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Extensions.DependencyInjection.ServiceProvider.ServiceAccessor, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].GetOrAdd(ServiceIdentifier key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IMauiHandlersFactory](IServiceProvider provider)
   at Microsoft.Maui.MauiContext.<.ctor>b__2_0()
   at System.Lazy`1[[Microsoft.Maui.IMauiHandlersFactory, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[Microsoft.Maui.IMauiHandlersFactory, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[Microsoft.Maui.IMauiHandlersFactory, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].CreateValue()
   at System.Lazy`1[[Microsoft.Maui.IMauiHandlersFactory, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Value()
   at Microsoft.Maui.MauiContext.get_Handlers()
   at Microsoft.Maui.Platform.ElementExtensions.SetHandler(INativeObject nativeElement, IElement element, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.SetApplicationHandler(IUIApplicationDelegate platformApplication, IApplication application, IMauiContext context)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at CommunityToolkitCrash.Program.Main(String[] args) in /Users/lars/workspace/Maui-Issues/CommunityToolkitCrash/CommunityToolkitCrash/Platforms/iOS/Program.cs:line 13

**Comment by Larhei** [comment]
Also tested with 9.0.1 and 9.0.2. Both are working fine

**Comment by jacob925** [comment]
9.0.X crashes for me also. same error.  I have to downgrade to 8.0.1

**Comment by ne0rrmatrix** [comment]
I tried replicating the issue. I was unable to do so. I used the sample from toolkit on Main with latest XCode 15.4, MauiVersion 8.0.80, and latest build from main. No issues on IOS 17.4 or 17.5. Same for Mac Catalyst. I then created a new app and added the toolkit to it. Nuget version 9.0.3. No issues on simulator. I also ran the sample app linked above with zero issues. At this time I need more information about the development environment and how you set it up to know what the issue is. I tested on a Mac mini M2.

**Comment by jacob925** [comment]
[MauiApp1.zip](https://github.com/user-attachments/files/16790130/MauiApp1.zip)
Bare bones app. nothing in it except the nuget package and .UseMauiCommunityToolkit() in the builder
crashes on start.
I am also using xCode 15.4 on a mac pro (screen shot:)
![Screenshot 2024-08-28 at 8 05 22 PM](https://github.com/user-attachments/assets/69831038-2847-41f2-aa4f-629444efbef2)
tested on iPhone 15 / 17.5 sim, iPad Pro 17.2 sim, and  iPad Pro 17.4 sim

**Comment by ne0rrmatrix** [comment]
@jacob925 I downloaded your sample after updating to latest dotnet version that came out 2 hours ago. 8.0.82. I was unable to replicate the issue. I was able to run it with zero issues on simulator running iOS 17.5 and 17.4. I have not modified your sample and ran as is. I did update my workloads before trying. Have you done that since updating dotnet?  ``` sudo dotnet workload update --source https://api.nuget.org/v3/index.json ```

**Comment by rbev** [comment]
I've just updated my frameworks & workloads after starting to see this error and i can't get it to work

Macbook pro M2

``` 
❯ dotnet workload list

Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
maui                       8.0.72/8.0.100        SDK 8.0.400

Use `dotnet workload search` to find additional workloads to install.

❯ dotnet --list-sdks
6.0.425 [/usr/local/share/dotnet/sdk]
8.0.401 [/usr/local/share/dotnet/sdk]

❯ dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.33 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.33 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by rbev** [comment]
Downgrading various packages doesn't seem to help for me

**Comment by bijington** [comment]
@jfversluis I recall you tweeted recently about avoiding upgrading to Sonoma but I don't recall the reason. Could this be a cause of the developers issues?

**Comment by rbev** [comment]
I updated to Sonoma AFTER I started seeing this issue.

Updating all my brew packages & dotnet SDKs caused me pain anyway so I decided in for a penny and clicked update on sonoma too)

**Comment by rbev** [comment]
I'm not sure when this issue started - I develop android-first for the most part.

But I do note that a release build in azure devops on sonoma 14.6.1 that has pushed to testflight yesterday afternoon with 9.0.3 works just fine

``` 
2024-08-28T07:29:53.0223290Z ##[section]Starting: Initialize job
2024-08-28T07:29:53.0422400Z Agent name: 'Hosted Agent'
2024-08-28T07:29:53.0422850Z Agent machine name: 'Mac-1724828530982'
2024-08-28T07:29:53.0423070Z Current agent version: '3.243.1'
2024-08-28T07:29:53.0454690Z ##[group]Operating System
2024-08-28T07:29:53.0454920Z macOS
2024-08-28T07:29:53.0455040Z 14.6.1
2024-08-28T07:29:53.0455150Z 23G93
2024-08-28T07:29:53.0455260Z ##[endgroup]
2024-08-28T07:29:53.0455420Z ##[group]Runner Image
2024-08-28T07:29:53.0455580Z Image: macos-14
2024-08-28T07:29:53.0455730Z Version: 20240827.1
2024-08-28T07:29:53.0456040Z Included Software: https://github.com/actions/runner-images/blob/macos-14/20240827.1/images/macos/macos-14-Readme.md
2024-08-28T07:29:53.0456450Z Image Release: https://github.com/actions/runner-images/releases/tag/macos-14%2F20240827.1
2024-08-28T07:29:53.0456710Z ##[endgroup]
```

**Comment by bijington** [comment]
Can you confirm if you have followed these steps:

https://github.com/CommunityToolkit/Maui/issues/2148#issuecomment-2308232294

**Comment by rbev** [comment]
Yup - definitely updated everything EXCEPT for the maui workload not updating to 8.0.80 as noted above I'm still being served up *.73

**Comment by rbev** [comment]
so after doing a release build my debug build worked.

then a clean + build failed again

**Comment by rbev** [comment]
building the community toolkit nugets locally has gotten it working for me - i can push my version of the package into our private artifact feed to get our dev team un-stuck for now.

**Comment by kelputoo** [comment]
It's also crashing for me on Android/iOS in the startup.

**Comment by bijington** [comment]
> building the community toolkit nugets locally has gotten it working for me - i can push my version of the package into our private artifact feed to get our dev team un-stuck for now.

It's sounding like there could be some strange environmental issue. I'm going to keep digging on my side to see if I can understand what is going on.

**Comment by bijington** [comment]
> It's also crashing for me on Android/iOS in the startup.

What is the exception you are seeing? This issue is specific to iOS as you will see it mentions iOS code in the stack trace

**Comment by rbev** [comment]
> > building the community toolkit nugets locally has gotten it working for me - i can push my version of the package into our private artifact feed to get our dev team un-stuck for now.
> 
> It's sounding like there could be some strange environmental issue. I'm going to keep digging on my side to see if I can understand what is going on.

So i thought that too - so I completely uninstalled all my dotnet sdk's and cleaned up the folders installing everything from scratch using brew/dotnet

It seems to affect everyone in our team. 
We don't have VS installed on our machines, only:

* Sonoma 14.6.1 (23G93)
* Xcode 15.4 (15F31d)
* Rider 2024.2.2 (Build #RD-242.20224.431)
* Dotnet sdk 8.0.401 (installed via https://github.com/isen-ng/homebrew-dotnet-sdk-versions)

however some of that was updated after the issue appeared so it's likely related to something else

**Comment by ne0rrmatrix** [comment]
I appear to be the only person who has a mac and has zero issues. The common theme I am getting is everyone is using homebrew and/or ryder. I am using vscode and I download dotnet from microsoft directly. I have had zero issues with building any of the samples provided and toolkit behaves like expected. I have latest 8.0.82 with Xcode 15.4 and using IOS 17.4 and 17.5.

**Comment by bijington** [comment]
I also haven't reproduce the issue so far. I am using Rider but not homebrew for my SDK source. I've messed up my workload installations now though so trying to tidy up

**Comment by kelputoo** [comment]
If you downgrade the Community Toolkit, it will work.
The same happened on Android to me, i fixed it by downgrading to the previous release version of Community Toolkit.
On iOS after downgrading, started working too.

**Comment by bijington** [comment]
I am running Rider and have workload 8.0.72 from SDK 8.0.401. I have then updated an existing project to use toolkit version 9.0.3 and all appears to be working as expected.

@rbev I don't know if this is part of the issue but I noticed that your SDK source is 8.0.400 whereas mine in 8.0.401. Unlikely to be the cause but it is a difference.

I will add that I have completely wiped my machine using this page to get myself into a clean state: https://gist.github.com/jonathanpeppers/63beb491a9185ac06710261536cc35c9
Not that I was seeing this issue but I had a LOT of old runtimes/SDKs installed

**Comment by rbev** [comment]
@bijington - I've definitely installed from 8.0.401 along the way, definitely after the full cleanup of sdks (along with removing net6/7) 

Happy to do it again tomorrow when I'm back in the office

I'll also make sure I force clean the bin/obj folders, I've remembered that sometimes Maui doesn't clean those properly on a `dotnet clean`

I'll also grab a list of all the dll md5 hashes so you can compare with what you've got in a build

**Comment by kelputoo** [comment]
Ok i was able to get some information.~
I was running the Community Tool Kit in the version **9.0.3**.
Downgrading to **9.0.2** works fine.

**Here's the error that appears using the 9.0.3 version.**
![image](https://github.com/user-attachments/assets/b8a90b16-c2b9-4efa-a6ad-87d24e7204bb)

_Running on iPhone XS Lastest IOS 17 Stable Version._

**Comment by bijington** [comment]
> Just want to share that I started getting this issue when upgrading to **MAUI Community Tool Kit 9.0.3**.
> 
> **I downgraded to 9.0.2 and it's all good again.**
> 
> 
> 
> This was on my Intel Mac Mini when deploying to physical devices (iOS 17.6.1)

Did you also update your MAUI workload when upgrading the toolkit version?

**Comment by dinisvieira** [comment]
> > Just want to share that I started getting this issue when upgrading to **MAUI Community Tool Kit 9.0.3**.
> > **I downgraded to 9.0.2 and it's all good again.**
> > This was on my Intel Mac Mini when deploying to physical devices (iOS 17.6.1)
> 
> Did you also update your MAUI workload when upgrading the toolkit version?

I have a "weird" workflow, I'm doing all nuget/project changes on Windows on Visual Studio.
No changes are done on Mac, just fetching latest changes and Clean/Build.

No changes to workloads also, I have been using MAUI nuget version 8.0.80 for a while now. (before any changes to MCT)
I have them set directly on the project.
```
<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.80" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.80" />
```

**Comment by bijington** [comment]
You still need to update your workloads. If you haven't done this on your Mac recently then can you do that and try using 9.0.3 of the toolkit again?

**Comment by brminnick** [comment]
This is likely a misconfiguration with your local environment. 

Please ensure you have installed the following items:
- [ ] Xcode 15.4.0
- [ ] Update to the latest stable version of Visual Studio (or Jet Brains Rider)
- [ ] Download/install the [latest stable version of .NET 8 (v8.0.400)](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)
- [ ] After installing .NET SDK v8.0.400, update to the latest stable version of .NET MAUI
  - On macOS, open the Terminal and enter the following command: `sudo dotnet workload install maui`
  - On Windows, open the command prompt (or Powershell) and enter the following command: `dotnet workload install maui`

**Comment by dinisvieira** [comment]
> This is likely a misconfiguration with your local environment.
> 
> Please ensure you have installed the following items:
> 
> * [ ]  Xcode 15.4.0
> * [ ]  Update to the latest stable version of Visual Studio (or Jet Brains Rider)
> * [ ]  Download/install the [latest stable version of .NET 8 (v8.0.400)](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)
> * [ ]  After installing .NET SDK v8.0.400, update to the latest stable version of .NET MAUI
>   
>   * On macOS, open the Terminal and enter the following command: `sudo dotnet workload install maui`
>   * On Windows, open the command prompt (or Powershell) and enter the following command: `dotnet workload install maui`

Yes, that was it. Updating .Net 8 did the trick. It's now working.

**Comment by rbev** [comment]
ok, I have it working

what worked was 

* update to latest .net SDK
* update workloads
* close IDE
* delete `/bin` `/obj` **<-- this is important**
* rebuild

What I suspect is the trigger here is that there is some MAUI build step that is using the assembly full name instead of file hashes to decide if the binary is up to date so switching versions of the library don't actually fix the issue and community toolkit doesn't have a version number stamped in the .dll

![image](https://github.com/user-attachments/assets/5f8b893f-c62a-40d0-801b-d4275401b182)


this could also affect libraries elsewhere in the build chain - hence the typeload exceptions because the assemblies name matched but the types didnt, potentially something between mismatched CommunityToolkit.Maui and CommunityToolkit.Maui.Core

**Comment by Larhei** [comment]
Updating like explained is fixing the issue for me. Thx for clarification.

**Comment by gwise-vision** [comment]
Please check the version of Microsoft.NET.ILLink.Tasks in Mac VS2022.

**Comment by MickBadran** [comment]
I wrestled with this for far too long and thank you for the suggestions along the way.
(did all the updates, reinstalls, clean, delete /bin /obj and nothing worked)

I just down graded to 9.0.2 and worked a treat.

Im using VS2022 (PC) -> Pair MAC -> xcode 15.4/mono.

Something is amiss and it's not on the compile it's on the launch. I've seen these 'cant load types...' error messages when something fails on the constructor of the class.

Love the experience so far.

**Comment by riccardominato** [comment]
Couldn't be possible to make this error less invasive? I updated my machine environment and all nugets and still having this error.

Xcode 16.0
iOS simulator 17.2

```
dotnet --version    
8.0.402
```

```
dotnet workload list       

ID carico di lavoro installato      Versioni del manifesto      Origine dell'installazione
------------------------------------------------------------------------------------------
maui-ios                            8.0.82/8.0.100              SDK 8.0.400               
maui-android                        8.0.82/8.0.100              SDK 8.0.400               
```

Running `dotnet workload update` doesn't update anything.

```
<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.91" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.91" />
<PackageReference Include="CommunityToolkit.Maui" Version="9.1.0" />
```

Maybe is this having something to do with all the question about supporting Xcode 16?

**Comment by bijington** [comment]
If we could make it less invasive we would but I don't believe we are causing it.

There is a chance it is related to Xcode 16, I'm surprised developers have updated to it already given MS only announced they supported it a day or two ago - perhaps I'm just cautious having been bitten by similar integration issues in the past.

One thing to try might be to uninstall all SDKs / workloads and only install the one you care about. There is a good wiki page I have to reference... let me find it

**Comment by riccardominato** [comment]
@bijington Unfortunately it's not that surprising.

I would have been very happy to delay the Xcode 16 transition, but after updating maui workloads, I was `forced` to install Xcode 16, otherwise the app doesn't build.

Moreover, Xcode seems to like to auto update.

Put these things together, and here we are :)

**Comment by bijington** [comment]
In future for managing Xcode versions I would thoroughly recommend using this tool https://github.com/XcodesOrg/XcodesApp

**Comment by bijington** [comment]
@riccardominato are you developing in a Mac or are you using a windows machine to connect to the Mac?

**Comment by riccardominato** [comment]
Thank you for your hints. Actually I use it, but the main problem is that I had to install Xcode 16 to make the MAUI app build.

I'm working on a Mac running MacOS Sonoma 14.7.

**Comment by MickBadran** [comment]
> This is typically down to a mismatch of versions on the build machines. What versions of dotnet do you have installed on both your Windows machine and Mac? Are they in sync?

Thanks @bijington, I'm currently developing on a PC using 'Pair to Mac' feature.

Clean build on the MAC and I was impressed with as part of the 'Pair to Mac' it checks dependencies and installs mono etc. what I need on the MAC. (.net9.xx rc1)

So I guess the thing that's missing with all of this is a dependency checker for both PC + Mac for MAUI iOS workloads.

Other products in VSCode do this - for e.g. Microsoft Logic Apps standard extension - checks if your machine has the latest bits and updates as required.

Currently this is all guess work across multiple platforms - and unfortunately Apple push us to xcode16+++ to keep publishing to app store.

**Comment by bijington** [comment]
Oh you are using .NET 9.0? We haven't added explicit support for that yet so I wouldn't expect it to be stable. Do you have any other workloads installed?

**Comment by MickBadran** [comment]
@bijington on my PC yes, but these .NET packages (.net9 rc1) were installed by the 'Pair to Mac' and Connect feature.

It was an automatic .NET check on the MAC and VSNET2022(PC) installed them via an SSH connection to the MAC

**Comment by mrdhockey87** [comment]
I am getting this problem if I update from version 9.0.3 to 9.1.0.  I am on a Windows system, my Mac is Sequia, however I still have Xcode 15.4 so I can pair to my mac and see my Simulators (I have Xcode 16 also), I have tried all of the suggestions on both my Windows and Mac systems so the Community Toolkit is the only thing that isn't current and updated on either system. I can run the app on an iOS Simulator if I set the version of the Toolkit to 9.0.3, however if I update to 9.1.0 I get this crash as it tries to start. Are there any other suggetions to fix this. Is there any setting in the Solution or .csproj file that isn't compatible with the Toolkit?
I have dotnet version 9.0.100-rc.1.24452.12 installed and workload version 9.0.100-rc.1.24453.3. However, I still have the app set for .Net 8.0.

**Comment by mrdhockey87** [comment]
After uninstalling .net 9, I still get the same error when running the app
`Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maccatalyst                17.5.8030/8.0.100      VS 17.11.35312.102 
android                    34.0.113/8.0.100       VS 17.11.35312.102 
ios                        17.5.8030/8.0.100      VS 17.11.35312.102 
maui-windows               8.0.82/8.0.100         VS 17.11.35312.102 `

**Comment by mrdhockey87** [comment]
After uninstalling .net 9, I still get the same error when running the app.

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maccatalyst                17.5.8030/8.0.100      VS 17.11.35312.102 
android                    34.0.113/8.0.100       VS 17.11.35312.102 
ios                        17.5.8030/8.0.100      VS 17.11.35312.102 
maui-windows               8.0.82/8.0.100         VS 17.11.35312.102

**Comment by amilici** [comment]
Why is this closed as not planned? There is obviously a bug here. I am getting the issue with:

dotnet 8.0.400

Workload version: 8.0.400

Installed Workload Id      Installation Source
----------------------------------------------
maui-android               SDK 8.0.400        
ios                        SDK 8.0.400        
android                    SDK 8.0.400  

"CommunityToolkit.Maui" Version="9.0.1"
"Microsoft.Maui.Controls" Version="8.0.40"
"Microsoft.Maui.Controls.Compatibility" Version="8.0.40"

Xcode 15.1
macOS Ventura 13.5.2

Simulator works fine but it happens on the device. It was happening on the simulator but it stopped.

**Comment by bijington** [comment]
@amilici please follow these steps: https://github.com/CommunityToolkit/Maui/issues/2148#issuecomment-2414761634

**Comment by brminnick** [comment]
We closed it because we cannot reproduce this error.

This is most likely a misconfiguration of your local environment. Please open a new Issue with a reproduction sample if you are unable to resolve your problem.

@amilici  Please ensure you have installed the following items:
- [ ] Xcode 16.0.0
- [ ] Update to the latest stable version of Visual Studio (or Jet Brains Rider)
- [ ] Download/install the [latest stable version of .NET 8 (v8.0.403)](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)
- [ ] After installing .NET SDK v8.0.403, update to the latest stable version of .NET MAUI
  - On macOS, open the Terminal and enter the following command: `sudo dotnet workload install maui`
  - On Windows, open the command prompt (or Powershell) and enter the following command: `dotnet workload install maui`
- [ ] Add a [`global.json`](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json) file to your application with the following parameters to ensure you're not using a unsupported preview version of .NET:

### global.json
```
{
  "sdk": {
    "version": "8.0.403",
    "rollForward": "latestFeature",
    "allowPrerelease": false
  }
}

```
