### ISSUE TITLE
[BUG] `TapGestureRecognizer` not triggered when in combination with `TouchBehavior` and `Border.Shadow`

### ISSUE THREAD

**Issue by FroggieFrog** [CommunityToolkit/Maui#2165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

A `TapGestureRecognizer` is not triggered when used in combination with a `TouchBehavior` and inside of a `Border` with a `Shadow`.

### Expected Behavior

The `TapGestureRecognizer` is triggered

### Steps To Reproduce

1. run the app from the repo **in Android 14**
2. click on the images
3. see that there is no `Toast` when clicked on the second image

### Link to public reproduction project repository

https://github.com/FroggieFrog/BugMauiShadowTouch

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.3
- OS: Android 14
- .NET MAUI: 8.0.82
```

**Comment by bijington** [comment]
Why can't you just use the `TouchGestureCompleted` event from the `TouchBehavior` and not bother with a `TapGestureRecognizer`?

**Comment by FroggieFrog** [comment]
1. I need to execute a Command -> `TouchBehavior` has a Command property, but BindingContext is not set
2. I can't attach a `EventToCommandBehavior` to another Behavior
3. I want to avoid code behind
4. I can't think of any reason why my wanted behavior should not be possible

**Comment by bijington** [comment]
I agree with point 4 but I was just trying to find a simpler solution for you. Can you set the `BindingContext` of the `TouchBehavior`?

**Comment by FroggieFrog** [comment]
Unfortunately no.
As soon as I add either `BindingContext` or `Command` to the `toolkit:TouchBehavior`, the app crashes. (screenshot and stacktrace are from WinUI, but same behavior on Android)
I don't even have to add the `Border` to make it crash.

#### Stacktrace

> Message = "Operation is not valid due to the current state of the object."
> 
>    at Microsoft.Maui.Controls.Binding.<ApplyRelativeSourceBinding>d__27.MoveNext()
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
>    at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

![grafik](https://github.com/user-attachments/assets/8920d6c5-7030-4a1c-8640-55451bb0da1c)

#### my code

```xaml
 <Border
     Grid.RowSpan="2"
     Grid.Column="1"
     Margin="0,40,0,0"
     HorizontalOptions="Center">
     <Border.Behaviors>
         <toolkit:TouchBehavior
             BindingContext="{Binding Source={RelativeSource AncestorType={x:Type viewmodels:MyViewModel}}}"
             Command="{Binding MyCommand}"
             HoveredOpacity="0.8"
             HoveredScale="0.9"
             PressedOpacity="0.6"
             PressedScale="0.8" />
     </Border.Behaviors>
     <!--<Border.GestureRecognizers>
         <TapGestureRecognizer Command="{Binding Source={RelativeSource AncestorType={x:Type viewmodels:MyViewModel}}, Path=MyCommand}" />
     </Border.GestureRecognizers>-->

     <Image Source="{Binding MyModel, Converter={StaticResource myConverter}}" />
 </Border>
```

**Comment by hansmbakker** [comment]
> As soon as I add either BindingContext or Command to the toolkit:TouchBehavior, the app crashes. (screenshot and stacktrace are from WinUI, but same behavior on Android)
> I don't even have to add the Border to make it crash.
> 
> Stacktrace
> Message = "Operation is not valid due to the current state of the object."

@FroggieFrog that one could be this issue - https://github.com/CommunityToolkit/Maui/issues/1783

**Comment by RafaelFernandesBR** [comment]
I'm hitting the same bug in production. Confirmed on a real Android device (not just emulator):
I'm hitting the same bug in production. Confirmed on a real Android device (not just emulator), and ended up going through a few more dead ends before landing on something that actually works reliably — writing it all up here in case it saves someone else the same loop.

- **Environment**: `CommunityToolkit.Maui` 13.0.0, `Microsoft.Maui.Controls` 10.0.60, `net10.0-android`.
- **Setup**: a `Frame` inside a `CollectionView.ItemTemplate` (virtualized grid) with a `TapGestureRecognizer` for tap, plus a `CommunityToolkit.Maui.Behaviors.TouchBehavior` on the same `Frame` for `LongPressCommand`.
- **Symptom**: with the `TouchBehavior` present, the `TapGestureRecognizer`'s `Command` stops firing on a genuine touch — tapping the cell does nothing. It only works when triggered via Android TalkBack (which calls `View.performClick()` directly, bypassing the touch pipeline).
- Removing the `TouchBehavior` entirely restores the `TapGestureRecognizer` immediately.

I don't have a fully confirmed root cause for the conflict itself — I decompiled `TouchBehavior` (13.0.0, `net10.0-android`) and it subscribes via `platformView.Touch +=`, the same multicast .NET-for-Android event `TapGestureRecognizer` itself uses (via `GesturePlatformManager`), so it's not simply a `SetOnTouchListener()` slot collision as I first assumed. Something about the combination still breaks tap reliably and reproducibly on my end though, so filing this in case it helps narrow it down, or in case it rings a bell for something specific to `Behavior`/handler lifecycle inside a recycled `CollectionView` cell.

**Two more gotchas I hit building a replacement**, in case they save someone a debugging session:

1. **A native `OnLongClickListener` alone doesn't fire on a real press either**, on an element that also has a `TapGestureRecognizer`. `TapGestureRecognizer`'s own `View.Touch` handler marks `ACTION_DOWN` as `Handled = true` for any element with a gesture recognizer, and per `View.dispatchTouchEvent()`, that skips `View.onTouchEvent()` for the event — exactly where Android schedules `checkForLongClick()`, which native `OnLongClickListener` depends on. A managed timer over `View.Touch` sidesteps this since it doesn't need `onTouchEvent()` to run at all (see below). TalkBack's "double-tap and hold" is unaffected since it dispatches `ACTION_LONG_CLICK` straight to `performLongClick()`, bypassing the touch pipeline — so you still want a native `OnLongClickListener` in parallel, just not as your only mechanism.

2. **A custom `Behavior<T>`'s own bindable properties don't reliably resolve XAML `Binding` markup extensions that expect an `Element`'s `Parent` chain — because `Behavior` isn't an `Element`.** I gave the behavior `Command`/`CommandParameter` bindable properties and tried two ways to wire them from inside a `DataTemplate`:
   - `Command="{Binding X, Source={x:Reference this}}"` (referencing the containing control by name) resolved to `null` **silently** — no XAML error, no crash, the native touch/long-click detection fired fine, but the bound command was always `null` so nothing happened. Only found this with a temporary diagnostic, since there's no exception to point at it.
   - `Command="{Binding Source={RelativeSource AncestorType=SomeViewModelType}, Path=X}"` (the pattern that works fine on `TapGestureRecognizer`, which is *also* not an `Element` — so this asymmetry is specific to custom `Behavior`s, not to "not being an Element" in general) instead **threw while instantiating the `DataTemplate`** — which, inside a `CollectionView` cell template, means the app crashes on the very first screen that renders the grid.

   The fix: don't bind `Command`/`CommandParameter` on the behavior via XAML at all. Resolve whatever you need in code, from `OnAttachedTo`, by walking `Element.Parent` yourself (a plain property, no markup extension involved) up to whatever ancestor holds your ViewModel, and read the current item straight from the attached `View`'s own `BindingContext` at invocation time — the same object `TapGestureRecognizer`'s `CommandParameter="{Binding .}"` would receive.

**One more consequence worth flagging**: once you have a working long-press, note that `TapGestureRecognizer` completes its tap on `ACTION_UP` **no matter how long the preceding hold was** — it has no built-in awareness that a long-press already fired on the same element. So releasing after a long-press also fires your tap command right after. If your long-press handler changes some state (e.g. entering a "selection mode") and your tap handler reacts to that same state (e.g. toggling selection), the release-triggered tap can immediately undo what the long-press just did. I fixed this at the app/ViewModel level with a short-lived marker (record the item + timestamp when long-press fires, consumed by the tap handler for the same item within ~2s) rather than in the touch layer, since the ordering (long-press always fires strictly before its own release-triggered tap, for one gesture) makes that reliable without touching gesture/event plumbing.

**Final working behavior**, combining both input modalities and avoiding the `Behavior`-isn't-an-`Element` binding trap:

```csharp
using Microsoft.Maui.Controls;

namespace YourApp.Behaviors;

/// <summary>
/// Long-press via two mechanisms in parallel, one per input modality:
///
/// 1) Real touch: a managed timer over the native View.Touch event (multicast in .NET-for-Android —
///    multiple independent subscribers get the same MotionEvent stream regardless of what others do
///    with Handled; this is the same event TapGestureRecognizer itself subscribes to). Never sets
///    e.Handled, so it doesn't interfere with TapGestureRecognizer's tap or CollectionView scrolling.
/// 2) TalkBack ("double-tap and hold"): a native LongClickable/OnLongClickListener registration,
///    since TalkBack dispatches ACTION_LONG_CLICK via View.performLongClick() directly, bypassing
///    the touch pipeline entirely (so it isn't affected by (1)'s constraint, and vice versa).
///
/// No Command/CommandParameter bindable properties: Behavior&lt;T&gt; isn't an Element, so XAML
/// markup extensions that expect a Parent chain (x:Reference, RelativeSource AncestorType) don't
/// reliably resolve on its own properties (the former silently resolves null; the latter throws
/// while instantiating a DataTemplate). Instead this walks Element.Parent itself, in code, and
/// reads the current item straight from the attached View's own BindingContext.
/// </summary>
public class LongPressBehavior : Behavior<View>
{
    private View? _attachedView;
    private YourAppViewModelBase? _viewModel; // replace with whatever base type/interface exposes your command

    protected override void OnAttachedTo(View bindable)
    {
        base.OnAttachedTo(bindable);
        _attachedView = bindable;
        bindable.HandlerChanging += OnHandlerChanging;
        bindable.HandlerChanged += OnHandlerChanged;
        bindable.Loaded += OnLoaded; // extra attach trigger, belt-and-suspenders for recycled cells
        if (bindable.Handler != null)
            Attach(bindable);
    }

    protected override void OnDetachingFrom(View bindable)
    {
        bindable.HandlerChanging -= OnHandlerChanging;
        bindable.HandlerChanged -= OnHandlerChanged;
        bindable.Loaded -= OnLoaded;
        Detach(bindable);
        _attachedView = null;
        _viewModel = null;
        base.OnDetachingFrom(bindable);
    }

    private void OnLoaded(object? sender, EventArgs e)
    {
        if (sender is View view && view.Handler != null)
            Attach(view);
    }

    // Handler is recreated when a CollectionView cell is recycled — detach from the OLD handler
    // explicitly (HandlerChanging exposes OldHandler) and attach to the new one in HandlerChanged.
    private void OnHandlerChanging(object? sender, HandlerChangingEventArgs e)
    {
#if ANDROID
        if (e.OldHandler?.PlatformView is Android.Views.View oldNative)
            DetachNative(oldNative);
#endif
    }

    private void OnHandlerChanged(object? sender, EventArgs e)
    {
        if (sender is not View view) return;

        if (view.Handler != null)
            Attach(view);
        else
            Detach(view);
    }

    /// <summary>Walks up from the attached element to find the page's ViewModel — replace the type check with your own.</summary>
    private static YourAppViewModelBase? FindViewModel(Element? element)
    {
        while (element != null)
        {
            if (element.BindingContext is YourAppViewModelBase viewModel)
                return viewModel;
            element = element.Parent;
        }
        return null;
    }

    private void InvokeLongPressCommand()
    {
        var view = _attachedView;
        if (view == null) return;

        _viewModel ??= FindViewModel(view);
        if (_viewModel == null) return;

        // Replace with however you read the item / invoke your command:
        var item = view.BindingContext;
        if (_viewModel.YourLongPressCommand.CanExecute(item))
            _viewModel.YourLongPressCommand.Execute(item);
    }

#if ANDROID
    private float _downX;
    private float _downY;
    private CancellationTokenSource? _longPressCts;

    private void Attach(View view)
    {
        if (view.Handler?.PlatformView is not Android.Views.View native) return;

        native.Touch -= OnNativeTouch; // avoid double-subscribing on a reused handler
        native.Touch += OnNativeTouch;

        native.LongClickable = true;
        native.LongClick -= OnNativeLongClick;
        native.LongClick += OnNativeLongClick;
    }

    private void Detach(View view)
    {
        if (view.Handler?.PlatformView is Android.Views.View native)
            DetachNative(native);
    }

    private void DetachNative(Android.Views.View native)
    {
        native.Touch -= OnNativeTouch;
        native.LongClick -= OnNativeLongClick;
        CancelPendingLongPress();
    }

    // Modality 1: real touch, timed in managed code.
    private void OnNativeTouch(object? sender, Android.Views.View.TouchEventArgs e)
    {
        var ev = e.Event;
        if (ev == null) return;

        // Never sets e.Handled: this only observes the touch to time the long-press, it doesn't
        // compete with TapGestureRecognizer's tap or with CollectionView scrolling.
        switch (ev.Action)
        {
            case Android.Views.MotionEventActions.Down:
                _downX = ev.GetX();
                _downY = ev.GetY();
                StartPendingLongPress();
                break;

            case Android.Views.MotionEventActions.Move:
                if (HasMovedBeyondTouchSlop(sender as Android.Views.View, ev))
                    CancelPendingLongPress();
                break;

            case Android.Views.MotionEventActions.Up:
            case Android.Views.MotionEventActions.Cancel:
                CancelPendingLongPress();
                break;
        }
    }

    // Modality 2: TalkBack's "double-tap and hold" → ACTION_LONG_CLICK → performLongClick().
    private void OnNativeLongClick(object? sender, Android.Views.View.LongClickEventArgs e)
    {
        InvokeLongPressCommand();
        e.Handled = true;
    }

    private void StartPendingLongPress()
    {
        CancelPendingLongPress();

        var cts = new CancellationTokenSource();
        _longPressCts = cts;
        var timeoutMs = Android.Views.ViewConfiguration.LongPressTimeout;

        _ = FireAfterDelayAsync(timeoutMs, cts.Token);
    }

    private async Task FireAfterDelayAsync(int delayMs, CancellationToken token)
    {
        try
        {
            await Task.Delay(delayMs, token);
        }
        catch (TaskCanceledException)
        {
            return;
        }

        if (token.IsCancellationRequested) return;

        if (_longPressCts != null && _longPressCts.Token == token)
        {
            _longPressCts.Dispose();
            _longPressCts = null;
        }

        InvokeLongPressCommand();
    }

    private void CancelPendingLongPress()
    {
        _longPressCts?.Cancel();
        _longPressCts?.Dispose();
        _longPressCts = null;
    }

    private bool HasMovedBeyondTouchSlop(Android.Views.View? native, Android.Views.MotionEvent ev)
    {
        var config = native?.Context != null ? Android.Views.ViewConfiguration.Get(native.Context) : null;
        var slop = config?.ScaledTouchSlop ?? 8;
        var dx = ev.GetX() - _downX;
        var dy = ev.GetY() - _downY;
        return (dx * dx) + (dy * dy) > slop * slop;
    }
#else
    private void Attach(View view) { }
    private void Detach(View view) { }
#endif
}
```

Usage, keeping the existing `TapGestureRecognizer` for tap untouched — no `Command`/`CommandParameter` attributes on the behavior at all:

```xml
<Frame.GestureRecognizers>
    <TapGestureRecognizer Command="{Binding TapCommand}" CommandParameter="{Binding .}" />
</Frame.GestureRecognizers>
<Frame.Behaviors>
    <behaviors:LongPressBehavior />
</Frame.Behaviors>
```

Hope this saves someone else the debugging loop I went through (five deploys before this one actually worked end to end, including a crash from the `RelativeSource` attempt) — happy to open a small repro repo if that's useful for triaging `TouchBehavior` itself.

- **Environment**: `CommunityToolkit.Maui` 13.0.0, `Microsoft.Maui.Controls` 10.0.60, `net10.0-android`.
- **Setup**: a `Frame` inside a `CollectionView.ItemTemplate` (virtualized grid) with a `TapGestureRecognizer` for tap, plus a `CommunityToolkit.Maui.Behaviors.TouchBehavior` on the same `Frame` for `LongPressCommand`.
- **Symptom**: with the `TouchBehavior` present, the `TapGestureRecognizer`'s `Command` stops firing on a genuine touch — tapping the cell does nothing. It only works when triggered via Android TalkBack (which calls `View.performClick()` directly, bypassing the touch pipeline), confirming the `TouchBehavior`'s native `OnTouchListener` is consuming the touch before the click can be dispatched.
- Removing the `TouchBehavior` entirely restores the `TapGestureRecognizer` immediately.

Digging a bit further with a decompiler into `Microsoft.Maui.Controls.dll` 10.0.60 (`GesturePlatformManager`/`InnerGestureListener`/`TapAndPanGestureDetector`), it looks like `TapGestureRecognizer` itself registers its own native touch handling via the safe `View.Touch` C# event (a multicast event — multiple independent subscribers can coexist on it fine). `TouchBehavior`, on the other hand, appears to call the native `SetOnTouchListener()` Java API directly, which *replaces* the single listener that backs `View.Touch`'s multicast dispatch — breaking every existing `View.Touch` subscriber, including `TapGestureRecognizer`'s own. That would explain why the two can't coexist on the same element.

One thing worth flagging for anyone else debugging this: I first tried keeping `TapGestureRecognizer` for tap and adding a **separate** native `OnLongClickListener`-based long-press (bypassing `TouchBehavior` for that part too) — that avoids the `SetOnTouchListener` collision, but it *still* doesn't reliably fire on a real touch-and-hold, because `TapGestureRecognizer`'s own `View.Touch` handler marks `ACTION_DOWN` as `Handled = true` whenever the element has any gesture recognizer, and per Android's own `View.dispatchTouchEvent()`, an `OnTouchListener` returning `true` prevents `View.onTouchEvent()` from running for that event — which is exactly where Android schedules the native `checkForLongClick()` that `OnLongClickListener` depends on. So a native long-click listener alongside `TapGestureRecognizer` on the same element also silently doesn't fire for a real press (it only "worked" via TalkBack's synchronous `performLongClick()`, which bypasses that whole pipeline).

**Workaround that actually works for both real touch and TalkBack**: implement the long-press timer yourself in managed code on top of the same `View.Touch` multicast event `TapGestureRecognizer` already uses, instead of relying on `TouchBehavior` or on `OnLongClickListener`/`checkForLongClick`. Since `View.Touch` is multicast, your handler receives the same touch stream regardless of what `TapGestureRecognizer`'s own handler does with `Handled`, so you're not fighting it:

```csharp
using System.Windows.Input;

namespace AcessGallery.Behaviors;

/// <summary>
/// Long-press implemented in managed code over the native View.Touch event (not over
/// OnLongClickListener/checkForLongClick, and not over CommunityToolkit.Maui.Behaviors.TouchBehavior).
/// View.Touch is a multicast .NET-for-Android event — the same mechanism TapGestureRecognizer itself
/// uses — so multiple independent subscribers coexist fine regardless of what others do with
/// e.Handled. This never sets e.Handled, so it doesn't interfere with TapGestureRecognizer's own tap
/// handling or with CollectionView scrolling. Duration/slop come from Android's own
/// ViewConfiguration, respecting the user's configured long-press timeout.
/// </summary>
public class LongPressBehavior : Behavior<View>
{
    public static readonly BindableProperty CommandProperty = BindableProperty.Create(
        nameof(Command), typeof(ICommand), typeof(LongPressBehavior));

    public ICommand? Command
    {
        get => (ICommand?)GetValue(CommandProperty);
        set => SetValue(CommandProperty, value);
    }

    public static readonly BindableProperty CommandParameterProperty = BindableProperty.Create(
        nameof(CommandParameter), typeof(object), typeof(LongPressBehavior));

    public object? CommandParameter
    {
        get => GetValue(CommandParameterProperty);
        set => SetValue(CommandParameterProperty, value);
    }

    protected override void OnAttachedTo(View bindable)
    {
        base.OnAttachedTo(bindable);
        bindable.HandlerChanging += OnHandlerChanging;
        bindable.HandlerChanged += OnHandlerChanged;
        if (bindable.Handler != null)
            Attach(bindable);
    }

    protected override void OnDetachingFrom(View bindable)
    {
        bindable.HandlerChanging -= OnHandlerChanging;
        bindable.HandlerChanged -= OnHandlerChanged;
        Detach(bindable);
        base.OnDetachingFrom(bindable);
    }

    // Handler is recreated when a CollectionView cell is recycled — detach from the OLD handler
    // explicitly (HandlerChanging exposes OldHandler) and attach to the new one in HandlerChanged.
    private void OnHandlerChanging(object? sender, HandlerChangingEventArgs e)
    {
#if ANDROID
        if (e.OldHandler?.PlatformView is Android.Views.View oldNative)
            DetachNative(oldNative);
#endif
    }

    private void OnHandlerChanged(object? sender, EventArgs e)
    {
        if (sender is not View view) return;

        if (view.Handler != null)
            Attach(view);
        else
            Detach(view);
    }

#if ANDROID
    private float _downX;
    private float _downY;
    private CancellationTokenSource? _longPressCts;

    private void Attach(View view)
    {
        if (view.Handler?.PlatformView is not Android.Views.View native) return;
        native.Touch -= OnNativeTouch; // avoid double-subscribing on a reused handler
        native.Touch += OnNativeTouch;
    }

    private void Detach(View view)
    {
        if (view.Handler?.PlatformView is Android.Views.View native)
            DetachNative(native);
    }

    private void DetachNative(Android.Views.View native)
    {
        native.Touch -= OnNativeTouch;
        CancelPendingLongPress();
    }

    private void OnNativeTouch(object? sender, Android.Views.View.TouchEventArgs e)
    {
        var ev = e.Event;
        if (ev == null) return;

        // Never sets e.Handled: this behavior only observes the touch to time the long-press,
        // it doesn't compete with TapGestureRecognizer's tap or with CollectionView scrolling.
        switch (ev.Action)
        {
            case Android.Views.MotionEventActions.Down:
                _downX = ev.GetX();
                _downY = ev.GetY();
                StartPendingLongPress();
                break;

            case Android.Views.MotionEventActions.Move:
                if (HasMovedBeyondTouchSlop(sender as Android.Views.View, ev))
                    CancelPendingLongPress();
                break;

            case Android.Views.MotionEventActions.Up:
            case Android.Views.MotionEventActions.Cancel:
                CancelPendingLongPress();
                break;
        }
    }

    private void StartPendingLongPress()
    {
        CancelPendingLongPress();

        var cts = new CancellationTokenSource();
        _longPressCts = cts;
        var timeoutMs = Android.Views.ViewConfiguration.LongPressTimeout;

        _ = FireAfterDelayAsync(timeoutMs, cts.Token);
    }

    private async Task FireAfterDelayAsync(int delayMs, CancellationToken token)
    {
        try
        {
            await Task.Delay(delayMs, token);
        }
        catch (TaskCanceledException)
        {
            return;
        }

        if (token.IsCancellationRequested) return;

        if (Command?.CanExecute(CommandParameter) == true)
            Command.Execute(CommandParameter);
    }

    private void CancelPendingLongPress()
    {
        _longPressCts?.Cancel();
        _longPressCts?.Dispose();
        _longPressCts = null;
    }

    private bool HasMovedBeyondTouchSlop(Android.Views.View? native, Android.Views.MotionEvent ev)
    {
        var config = native?.Context != null ? Android.Views.ViewConfiguration.Get(native.Context) : null;
        var slop = config?.ScaledTouchSlop ?? 8;
        var dx = ev.GetX() - _downX;
        var dy = ev.GetY() - _downY;
        return (dx * dx) + (dy * dy) > slop * slop;
    }
#else
    private void Attach(View view) { }
    private void Detach(View view) { }
#endif
}
```

Usage, keeping the existing `TapGestureRecognizer` for tap untouched:

```xml
<Frame.GestureRecognizers>
    <TapGestureRecognizer Command="{Binding TapCommand}" CommandParameter="{Binding .}" />
</Frame.GestureRecognizers>
<Frame.Behaviors>
    <behaviors:LongPressBehavior Command="{Binding LongPressCommand}" CommandParameter="{Binding .}" />
</Frame.Behaviors>
```

This is admittedly re-implementing a slice of what `TouchBehavior` already tries to do, but scoped to just long-press and built on the same `View.Touch` multicast mechanism `TapGestureRecognizer` itself relies on, instead of a competing `SetOnTouchListener()`/`OnLongClickListener` call. Hope this saves someone else the same debugging loop — happy to open a small repro repo if that's useful for triaging `TouchBehavior` itself.
