### ISSUE TITLE
[BUG] App crashes when using CommunityToolkit.Maui.MediaElement 4.1.0+

### ISSUE THREAD

**Issue by KeithBoynton** [CommunityToolkit/Maui#2216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When updating CommunityToolkit.Maui.MediaElement from 4.0.1 to 4.1.0 the following crash occurs on startup on iOS and MacCatalyst:

```
System.TypeLoadException: Could not set up parent class, due to: Invalid generic instantiation assembly:/Users/keithboynton/Documents/trackhunter-maui/Trackhunter/bin/Debug/net8.0-maccatalyst/maccatalyst-x64/Trackhunter.app/Contents/MonoBundle/Microsoft.Maui.dll type:ViewHandler`2 member:(null)
  at at CommunityToolkit.Maui.AppBuilderExtensions.<>c.<UseMauiCommunityToolkitMediaElement>b__0_0(IMauiHandlersCollection h)
  at at Microsoft.Maui.Hosting.HandlerMauiAppBuilderExtensions.HandlerRegistration.AddRegistration(IMauiHandlersCollection builder)
  at at Microsoft.Maui.Hosting.Internal.MauiHandlersFactory.CreateHandlerCollection(IEnumerable`1 registrationActions)
  at at Microsoft.Maui.Hosting.Internal.MauiHandlersFactory..ctor(IEnumerable`1 registrationActions)
  at at Microsoft.Maui.Hosting.HandlerMauiAppBuilderExtensions.<>c.<ConfigureMauiHandlers>b__1_0(IServiceProvider sp)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
  at at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
  at at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
  at at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Extensions.DependencyInjection.ServiceProvider.ServiceAccessor, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].GetOrAdd(ServiceIdentifier key, Func`2 valueFactory)
  at at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
  at at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
  at at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
  at at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
  at at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
  at at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IMauiHandlersFactory](IServiceProvider provider)
  at at Microsoft.Maui.MauiContext.<.ctor>b__2_0()
  at at System.Lazy`1[[Microsoft.Maui.IMauiHandlersFactory, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ViaFactory(LazyThreadSafetyMode mode)
  at at System.Lazy`1[[Microsoft.Maui.IMauiHandlersFactory, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
  at at System.Lazy`1[[Microsoft.Maui.IMauiHandlersFactory, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].CreateValue()
  at at System.Lazy`1[[Microsoft.Maui.IMauiHandlersFactory, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Value()
  at at Microsoft.Maui.MauiContext.get_Handlers()
  at at Microsoft.Maui.Platform.ElementExtensions.SetHandler(INativeObject nativeElement, IElement element, IMauiContext context)
  at at Microsoft.Maui.Platform.ElementExtensions.SetApplicationHandler(IUIApplicationDelegate platformApplication, IApplication application, IMauiContext context)
  at at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
  at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:58
  at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:94
  at Trackhunter.Program.Main(String[] args) in /Users/keithboynton/Documents/trackhunter-maui/Trackhunter/Platforms/MacCatalyst/Program.cs:13
```

It works fine in Windows and Android. Also, 4.0.1 works fine on all environments. Also, 4.1.1 crashes too on iOS and MacCatayst.

### Expected Behavior

I expect it to not crash

### Steps To Reproduce

1. Open and run solution from the reproduction repository
2. Run it on iOS or MacCatalyst and observe it crash
3. Run it on Windows or Android and observe it run as expected

### Link to public reproduction project repository

https://bitbucket.org/KeithBoynton/media-element-crash

### Environment

```markdown
- .NET MAUI CommunityToolkit: 4.1.0 +
- .NET MAUI: 8.0.90
```

**Comment by ne0rrmatrix** [comment]
I looked at your sample and you are missing some entries in you `PList` file  for `MediaElement`. 
``` 
<key>UIBackgroundModes</key>
<array>
    <string>audio</string>
</array> 
``` 
 Can you add the above to the `PList` file. You can read about the device specific requirements here: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/mediaelement?tabs=ios  for `IOS`. You should also look at the `MacOS` tab and adjust your `PList` for MacOS, and the same on the Android tab.

**Comment by KeithBoynton** [comment]
Appreciate you taking a look so quickly @ne0rrmatrix 

Apologies I forgot to update the plist entries in the reproduction project, although I do have those setup correctly in my main project. I've updated the reproduction project plist files now but it still exhibits the same crashing behaviour on iOS and MacCatalyst.

**Comment by bijington** [comment]
This looks like a duplicate of https://github.com/CommunityToolkit/Maui/issues/2148 can you please try following the steps here https://github.com/CommunityToolkit/Maui/issues/2148#issuecomment-2308232294

**Comment by KeithBoynton** [comment]
I can confirm the steps in the ticket you linked did resolve the issue, thank you
