### ISSUE TITLE
[BUG] MediaElement not supported in a DataTemplate on a Page with multiple `ItemView` controls

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#2247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

On iOS, when using a MediaElement in a `DataTemplate` on a page that contains multiple `ItemsViews`, the following exception is thrown:

```
System.NotSupportedException: MediaElement does not currently support pages containing multiple ItemsViews (eg multiple CarouselViews + CollectionViews)
   at CommunityToolkit.Maui.Core.Views.MauiMediaElement.TryGetItemsViewOnPage(Page currentPage, ItemsView& itemsView) in /Users/minnbran/GitHub/CommunityToolkit.Maui/src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.macios.cs:line 104
   at CommunityToolkit.Maui.Core.Views.MauiMediaElement..ctor(AVPlayerViewController playerViewController, MediaElement virtualView) in /Users/minnbran/GitHub/CommunityToolkit.Maui/src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.macios.cs:line 52
   at CommunityToolkit.Maui.Core.Handlers.MediaElementHandler.CreatePlatformView() in /Users/minnbran/GitHub/CommunityToolkit.Maui/src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.macios.cs:line 27
   at Microsoft.Maui.Handlers.ViewHandler`2[[CommunityToolkit.Maui.Views.MediaElement, CommunityToolkit.Maui.MediaElement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[CommunityToolkit.Maui.Core.Views.MauiMediaElement, CommunityToolkit.Maui.MediaElement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCreatePlatformView()
   at Microsoft.Maui.Handlers.ViewHandler.OnCreatePlatformElement()
   at Microsoft.Maui.Handlers.ElementHandler.CreatePlatformElement()
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[CommunityToolkit.Maui.Views.MediaElement, CommunityToolkit.Maui.MediaElement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[CommunityToolkit.Maui.Core.Views.MauiMediaElement, CommunityToolkit.Maui.MediaElement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[CommunityToolkit.Maui.Views.MediaElement, CommunityToolkit.Maui.MediaElement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[CommunityToolkit.Maui.Core.Views.MauiMediaElement, CommunityToolkit.Maui.MediaElement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.BorderHandler.UpdateContent(IBorderHandler handler)
   at Microsoft.Maui.Handlers.BorderHandler.MapContent(IBorderHandler handler, IBorderView border)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IBorderView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IBorderHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IBorderView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.BorderHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IBorderView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ViewExtensions.ToHandler(IView view, IMauiContext context)
   at Microsoft.Maui.Controls.Handlers.Items.TemplateHelpers.GetHandler(View view, IMauiContext context)
   at Microsoft.Maui.Controls.Handlers.Items.TemplatedCell.Bind(DataTemplate template, Object bindingContext, ItemsView itemsView)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.CarouselView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].UpdateTemplatedCell(TemplatedCell cell, NSIndexPath indexPath)
   at Microsoft.Maui.Controls.Handlers.Items.CarouselViewController.GetCell(UICollectionView collectionView, NSIndexPath indexPath)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
   at CommunityToolkit.Maui.Sample.Program.Main(String[] args) in /Users/minnbran/GitHub/CommunityToolkit.Maui/samples/CommunityToolkit.Maui.Sample/Platforms/iOS/Program.cs:line 7
```

This is a known bug where a `NotSupportedException` is thrown:

https://github.com/CommunityToolkit/Maui/blob/ed06645844df6aa05216eaab44b984f65020be09/src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.macios.cs#L104

### Expected Behavior

The developer should be able to use MediaElement despite multiple ItemsViews in use on the page.

### Steps To Reproduce

1. On an iOS device, launch CommunityToolkit.Maui.Sample
2. In CommunityToolkit.Maui.Sample, navigate to Views -> MediaElementCarouselPage
3. Confirm app crashes

### Link to public reproduction project repository

https://github.com/communitytoolkit/maui

### Environment

```markdown
- .NET MAUI CommunityToolkit MediaElement: v4.1.2
- OS: iOS
- .NET MAUI:
 [maui]
   Installation Source: SDK 8.0.400
   Manifest Version:    8.0.82/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.82/WorkloadManifest.json
   Install Type:        FileBased
```

**Comment by orlandommb** [comment]
any news on this ?

**Comment by ne0rrmatrix** [comment]
@orlandommb Can you test the PR linked above and see if it fixes the issue for you?

**Comment by rubendmribeiro** [comment]
Yap, this is also happening to me.
I have a MediaElement inside of a CollectionView (in my case SfListView) and it just doesn't work on iOS, got instant crash, can't even see any logs related to the crash, but it's from the MediaElement, because if i remove it, i can run the app normally.
iOS 26.3 (last version)

**Comment by AnthonyLatty** [comment]
Any update on this?

**Comment by jingliancui** [comment]
hi team, Any update on this？ thanks

**Comment by follesoe** [comment]
Another data point from a .NET MAUI 10.0.100 / `CommunityToolkit.Maui.MediaElement` 10.0.0 app, in case it helps validate #3222.

**Setup:** iOS app using native embedding (`UseMauiEmbeddedApp`, each `ContentPage` hosted through `ToUIViewController` in a native `UINavigationController`), a page with three `CarouselView`s, and a `MediaElement` in the `ItemTemplate` of one of them.

**1. `Cannot find current page`.** Inside a `DataTemplate` the constructor always ends up in the `TryGetCurrentPage` fallback, because both `TemplatedCell.Bind` (`TemplateHelpers.GetHandler` before `AddLogicalChild`) and `TemplatedCell2.BindVirtualView` (`ToPlatform` before `AddLogicalChild`) create the platform view before the content is parented, so `Element.Parent` is still null while `MauiMediaElement` is constructed. In an embedded app `Application.Current.Windows[0].Page` is null, so that fallback throws `InvalidOperationException: Cannot find current page` (what we see in production) rather than the `NotSupportedException` reported here; with a page it would hit the multiple-ItemsViews check anyway.

**2. Wrong view controller when the parent chain *is* available.** We worked around (1) by wrapping the `MediaElement` in a `ContentView` that only instantiates it in `Loaded`, i.e. after the cell content has been parented. The constructor then takes the `TryFindParent<Page>` branch and adds the `AVPlayerViewController` as a child of the *page's* view controller, and UIKit aborts as soon as the player view enters the hierarchy (observed with `CarouselViewHandler` pinned):

```
UIViewControllerHierarchyInconsistency: child view controller:<AVPlayerViewController> should have parent view controller:<Microsoft_Maui_Controls_Handlers_Items_CarouselViewController> but actual parent is:<...PageViewController>
```

The nearest view controller in the responder chain is the carousel's `UICollectionViewController`, and that is the only parent UIKit accepts. This is not specific to embedding: any `MediaElement` created lazily inside an `ItemsView` template (a poster image first, the player on tap, and so on) reaches the page through `Parent` and takes the same branch.

**Workaround** that works for us with both `CarouselViewHandler` and `CarouselViewHandler2`: a mapping appended to `MediaElementHandler.PropertyMapper` that re-parents the player to the nearest `UIViewController` in the responder chain of the `MediaElement`'s parent platform view.

```csharp
MediaElementHandler.PropertyMapper.AppendToMapping("ParentViewController", (handler, mediaElement) =>
{
	if (handler.PlatformView.Subviews.FirstOrDefault()?.NextResponder is not AVPlayerViewController player)
	{
		return;
	}

	// Walk Element.Parent to the first ancestor with a platform view, then NextResponder up to a UIViewController.
	var host = FindHostViewController(mediaElement);
	if (host?.View is null || player.ParentViewController == host)
	{
		return;
	}

	player.WillMoveToParentViewController(null);
	player.RemoveFromParentViewController();
	host.AddChildViewController(player);
	player.DidMoveToParentViewController(host);
});
```

Resolving the parent from the UIKit responder chain in `MovedToSuperview` / `MovedToWindow`, as #3222 does, covers all of the above without any app-side code.
