### ISSUE TITLE
Shell.Current.GotoAsync("..") app crash on windows when navigating back from a page that implements map control with this exception : PlatformView cannot be null here

### ISSUE THREAD

**Issue by MahmoudAlEssawi** [CommunityToolkit/Maui#2366]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

After upgrading to .net 9
and CommunityToolkit.Maui.Maps nuget to 2.0.4

when navigating back from a page that implements a map control

this happens on Windows only

 PlatformView cannot be null here

at Microsoft.Maui.Handlers.ViewHandler`2.get_PlatformView()
at CommunityToolkit.Maui.Maps.Handlers.MapHandlerWindows.DisconnectHandler(FrameworkElement platformView)
at Microsoft.Maui.Handlers.ViewHandler`2.OnDisconnectHandler(FrameworkElement platformView)
at Microsoft.Maui.Handlers.ViewHandler.OnDisconnectHandler(Object platformView)
at Microsoft.Maui.Handlers.ElementHandler.DisconnectHandler(Object platformView)
at Microsoft.Maui.Handlers.ElementHandler.Microsoft.Maui.IElementHandler.DisconnectHandler()
at Microsoft.Maui.ViewExtensions.DisconnectHandlers(IView view)
at Microsoft.Maui.Controls.Page.<SendNavigatedFrom>b__111_0()
at Microsoft.Maui.Platform.FrameworkElementExtensions.<>c__DisplayClass11_0.<OnUnloaded>b__2(Object _, RoutedEventArgs __)
at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)

### Expected Behavior

To navigate back normally

### Steps To Reproduce

setup the CommunityToolkit.Maui.Maps nuget version: 2.0.4

Create a page.

add map control,

run on Windows machine

try navigating to this page then navigate back.

### Link to public reproduction project repository

https://github.com/FaithfulDev/MapGoBackBugMinimal

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.1.1
- OS: Windows 11
- .NET MAUI: 9.0.10
- CommunityToolkit.Maui.Maps nuget to 2.0.4
```

**Comment by pictos** [comment]
@MahmoudAlEssawi this package isn't compatible with the .NET 9 yet.

**Comment by MahmoudAlEssawi** [comment]
When will the compatible version be released approximately?

**Comment by bijington** [comment]
That's a bit of an unknown right now. We are blocked by this issue https://github.com/dotnet/maui/issues/25871. I am planning on looking at it this week to speed things up but I can't give any indication how long that will take

**Comment by vhugogarcia** [comment]
@MahmoudAlEssawi the issue that was blocking us has been fixed and merged on the latest .NET MAUI version. Could you please help us to test again by upgrading .NET MAUI and .NET MAUI Community Toolkit?

I'm closing this ticket, however, if the issue re-appears again, we can re-open it.

Thank you

**Comment by MahmoudAlEssawi** [comment]
I  updated Maui controls and community toolkit to the latest version and then try to open the page that contains the map control on Windows >> This exception was thrown:

A method was called at an unexpected time.

ExecuteScriptAsync(): Failed because a valid CoreWebView2 is not present. Make sure one was created, for example by calling EnsureCoreWebView2Async() API.
