### ISSUE TITLE
[Bug] Error clearing ObservableCollection on iOS / macOS

### ISSUE THREAD

**Issue by gavinb80** [CommunityToolkit/Maui#488]
### Description

When using a **ObservableCollection** in my project and displaying via a ListView, I have an issue when clearing the content of the ObservableCollection.

When calling i**ncidentList.Clear();** it works fine on Android, but on iOS and MacOS I get the error "Object reference not set to an instance of an object." 

### Stack Trace

System.NullReferenceException: Object reference not set to an instance of an object.
  at at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UnevenListViewDataSource.ClearPrototype()
  at at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UnevenListViewDataSource.InvalidatingPrototypicalCellCache()
  at at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.ListViewDataSource.InvalidatePrototypicalCellCache()
  at at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.InvalidateCellCache()
  at at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UpdateItems(NotifyCollectionChangedEventArgs e, Int32 section, Boolean resetWhenGrouped)
  at at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
  at at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
  at at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnProxyCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
  at at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
  at at Microsoft.Maui.Controls.ListProxy.<>c__DisplayClass34_0.<OnCollectionChanged>b__0()
  at at Microsoft.Maui.Dispatching.Dispatcher.<>c__DisplayClass9_0.<DispatchImplementation>b__0()
  at at CoreFoundation.DispatchQueue.static_dispatcher_to_managed(IntPtr context)
  at at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
  at DsfrsApp.Program.Main(String[] args) in /Users/gavinbeard/Projects/DsfrsApp/DsfrsApp/Platforms/iOS/Program.cs:13

### MainPageViewModel.cs
```
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using DsfrsApp.Models;
using Newtonsoft.Json;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Xml;

namespace DsfrsApp.ViewModel;

public partial class MainViewModel : ObservableObject
{
    [ObservableProperty]
    ObservableCollection<IncidentCategoryModel> incidentCategories;

    [ObservableProperty]
    ObservableCollection<Item> items;

    [ObservableProperty]
    bool listRefreshing = false;

    public RelayCommand ReloadTaskCommand { get; }

    public MainViewModel()
    {
        ReloadTaskCommand = new RelayCommand(GetIncidents);
        incidentCategories = new ObservableCollection<IncidentCategoryModel>();
        items = new ObservableCollection<Item>();
    }

    async void GetIncidents()
    { 
        await getIncidentDetails("https://www.somesite.com/rss-feed.xml");
    }

    async Task getIncidentDetails(string feedUrl)
    {

        ListRefreshing = true;

        HttpClient client = new()
        {
            Timeout = new TimeSpan(0, 0, 20)
        };

        client.DefaultRequestHeaders.UserAgent.Clear();
        client.DefaultRequestHeaders.Add("User-Agent", "DsfrAppTest");

        await Task.Run(() =>
        {
            using var webResponse =  client.GetAsync(feedUrl, HttpCompletionOption.ResponseHeadersRead);
            using var downloadStream = webResponse.Result.Content.ReadAsStreamAsync().Result;

            StreamReader reader = new StreamReader(downloadStream);
            string xmlData = reader.ReadToEnd();
            XmlDocument xmlDocument = new();

            xmlDocument.LoadXml(xmlData);
            var jsonText = JsonConvert.SerializeXmlNode(xmlDocument);

            var incidents = Incident.FromJson(jsonText);
            Items.Clear();

            foreach (var incident in incidents.Rss.Channel.Item.Take(500))
            {
                Items.Add(incident);
            }

            var catDetail =
                from item in Items
                group item by item.Title into catList
                select new
                {
                    Title = catList.Key,
                    Count = catList.Count()
                };

            IncidentCategories.Clear();
            ListRefreshing = false;

            foreach (var cat in catDetail)
            {
                IncidentCategories.Add(new IncidentCategoryModel()
                {
                    ItemCount = cat.Count,
                    Title = cat.Title
                });
            }
        });
    }
}
```

### MainView.Xml

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="DsfrsApp.MainPage"
             xmlns:viewmodel="clr-namespace:DsfrsApp.ViewModel"
             x:DataType="viewmodel:MainViewModel"
             xmlns:models="clr-namespace:DsfrsApp.Models">
			 
        <StackLayout 
            Padding="8"
            HorizontalOptions="FillAndExpand"
            VerticalOptions="FillAndExpand">

            <Button 
                    x:Name="btnFetch"
                    Text="Fetch Data"
                    Command="{Binding ReloadTaskCommand}"
                    Margin="8"/>

            <ListView
                ItemsSource="{Binding IncidentCategories}"
                HasUnevenRows="True"
                VerticalOptions="FillAndExpand"
                ItemSelected="ListView_ItemSelected"
                IsPullToRefreshEnabled="True"
                RefreshCommand="{Binding ReloadTaskCommand}"
                IsRefreshing="{Binding ListRefreshing, Mode=TwoWay}">

                <ListView.ItemTemplate>
                    <DataTemplate
                        x:DataType="models:IncidentCategoryModel">
                        <ViewCell>
                            <Grid
                                Padding="8">

                                <Grid.RowDefinitions>
                                    <RowDefinition Height="Auto" />
                                    <RowDefinition Height="Auto" />
                                </Grid.RowDefinitions>

                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="Auto" />
                                    <ColumnDefinition Width="Auto" />
                                </Grid.ColumnDefinitions>

                                <Rectangle
                                    WidthRequest="60"
                                    HeightRequest="60"
                                    BackgroundColor="lightblue"
                                    Margin="8"
                                    Grid.Column="0"
                                    Grid.RowSpan="2" />
                                   
                               
                                 <Label Grid.Column="1"
                                    Grid.Row="0"
                                    Text="{Binding Title}"
                                    FontAttributes="Bold"
                                    FontSize="Title"/>

                                 <Label Grid.Column="1"
                                    Grid.Row="1"
                                    Text="{Binding itemCountText}"
                                    FontSize="Subtitle" />

                            </Grid>
                        </ViewCell>

                    </DataTemplate>

                </ListView.ItemTemplate>

            </ListView>

        </StackLayout>
</ContentPage>
```

**Comment by VladislavAntonyuk** [comment]
You should transfer this issue to dotnet/maui repo
