### ISSUE TITLE
[Bug] Popup, Microsoft.Maui.Platform.HandlerNotFoundException: 'Handler not found for view ...'

### ISSUE THREAD

**Issue by 8m0** [CommunityToolkit/Maui#492]
Hello, 
I get `Microsoft.Maui.Platform.HandlerNotFoundException: 'Handler not found for view fortestingshit.Controls.SimpP.'` exception.
I've seen Microsoft documentation and other sources, same error anyway. 

### Stack Trace

```
Microsoft.Maui.Platform.HandlerNotFoundException
  HResult=0x80131500
  Message=Handler not found for view fortestingshit.Controls.SimpP.
  Source=Microsoft.Maui
  StackTrace:
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at CommunityToolkit.Maui.Views.PopupExtensions.PlatformShowPopup(Popup popup, IMauiContext mauiContext)
   at CommunityToolkit.Maui.Views.PopupExtensions.PlatformShowPopupAsync(Popup popup, IMauiContext mauiContext)
   at CommunityToolkit.Maui.Views.PopupExtensions.ShowPopupAsync[TPopup](Page page, TPopup popup)
   at fortestingshit.MainPage.<OnCounterClicked>d__1.MoveNext() in ...\fortestingshit\MainPage.xaml.cs:line 17
```

### Project to test the error
[Repository](https://github.com/8m0/Popup-HandlerNotFoundException)

Steps:
1. Open project
2. Click the "Click me to open popup" button

Ide etc.:
- IDE: Microsoft Visual Studio Community 2022, Version 17.3.0 Preview 2.0
- Platform Target Frameworks: 
    Android, Windows
- CommunityToolkit.Maui version 1.0.0

**Comment by bijington** [comment]
You can see how to do it from the readme on the repo: https://github.com/CommunityToolkit/Maui

I thought we had this information on our docs page but I can't see it.

**Comment by 8m0** [comment]
How could i miss that... Didn't even think it could be there... Thanks for the help

**Comment by bijington** [comment]
We all miss things 😄 I'll make sure I get some information up on the docs pages to provide another place to explain it. Let me know if this solves the issue
