### ISSUE TITLE
[BUG] Adding animation crashes app in .NET 7 RC1

### ISSUE THREAD

**Issue by r-work** [CommunityToolkit/Maui#678]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

It breaks when you add animation behavior.
Using the default project sample:

```XAML
<Button
    x:Name="CounterBtn"
    Text="Click me"
    SemanticProperties.Hint="Counts the number of times you click"
    Clicked="OnCounterClicked"
    HorizontalOptions="Center">
    <Button.Behaviors>
        <toolkit:AnimationBehavior>
            <toolkit:AnimationBehavior.AnimationType>
                <toolkit:FadeAnimation Length="10" Opacity="1" />
            </toolkit:AnimationBehavior.AnimationType>
        </toolkit:AnimationBehavior>
    </Button.Behaviors>
</Button>
```

### Expected Behavior

Not to crash.

### Steps To Reproduce

1. Run project in the android emulator.

### Link to public reproduction project repository

https://github.com/r-work/MauiApp4

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS: Android API 24
- .NET MAUI: NET 7 RC1
```

### Anything else?

Output:

```
**System.Reflection.TargetInvocationException:** 'Exception has been thrown by the target of an invocation.'

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[mono-rt]  ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[mono-rt]  ---> System.MissingMethodException: Method not found: void Microsoft.Maui.Controls.TapGestureRecognizer.add_Tapped(System.EventHandler)
[mono-rt]    at Microsoft.Maui.Controls.Behavior`1[[Microsoft.Maui.Controls.VisualElement, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnAttachedTo(BindableObject bindable) in D:\a\_work\1\s\src\Controls\src\Core\Interactivity\Behavior.cs:line 47
[mono-rt]    at Microsoft.Maui.Controls.Behavior.Microsoft.Maui.Controls.IAttachedObject.AttachTo(BindableObject bindable) in D:\a\_work\1\s\src\Controls\src\Core\Interactivity\Behavior.cs:line 23
[mono-rt]    at Microsoft.Maui.Controls.AttachedCollection`1[[Microsoft.Maui.Controls.Behavior, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].InsertItem(Int32 index, Behavior item) in D:\a\_work\1\s\src\Controls\src\Core\Interactivity\AttachedCollection.cs:line 61
[mono-rt]    at System.Collections.ObjectModel.Collection`1[[Microsoft.Maui.Controls.Behavior, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Add(Behavior item)
[mono-rt]    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[mono-rt]    --- End of inner exception stack trace ---
[mono-rt]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[mono-rt]    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
[mono-rt]    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.TryAddValue(BindableObject bindable, BindableProperty property, Object value, IServiceProvider serviceProvider, Exception& exception) in D:\a\_work\1\s\src\Controls\src\Xaml\ApplyPropertiesVisitor.cs:line 812
[mono-rt]    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.TrySetValue(Object element, BindableProperty property, Boolean attached, Object value, IXmlLineInfo lineInfo, IServiceProvider serviceProvider, Exception& exception) in D:\a\_work\1\s\src\Controls\src\Xaml\ApplyPropertiesVisitor.cs:line 618
[mono-rt]    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.TrySetPropertyValue(Object element, XmlName propertyName, String xKey, Object value, Object rootElement, IXmlLineInfo lineInfo, IServiceProvider serviceProvider, Exception& xpe) in D:\a\_work\1\s\src\Controls\src\Xaml\ApplyPropertiesVisitor.cs:line 417
[mono-rt]    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo) in D:\a\_work\1\s\src\Controls\src\Xaml\ApplyPropertiesVisitor.cs:line 373
[mono-rt]    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ElementNode node, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\ApplyPropertiesVisitor.cs:line 120
[mono-rt]    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 159
[mono-rt]    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 153
[mono-rt]    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 155
[mono-rt]    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 155
[mono-rt]    at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 212
[mono-rt]    at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 210
[mono-rt]    at Microsoft.Maui.Controls.Xaml.XamlLo
```

**Comment by VladislavAntonyuk** [comment]
We do not support .net 7 yet. The PR for this is in draft. Most likely we’ll add it as preview with rc2. And final release after .net MAUI 7 release
