### ISSUE TITLE
Toast inside WeakReferenceMessenger event throws NULL

### ISSUE THREAD

**Issue by FM1973** [CommunityToolkit/Maui#786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I´m trying to use a toast message inside a Handler for a weakreferencemessenger in my BaseViewModel.
Calling await toast.Show results in a Null reference exception.
I also tried to call it inside a Dispatch - same result.

### Expected Behavior

the toast should be shown.
Outside of a weakreferencemessenger callback it works without any problem.

### Steps To Reproduce

Create a waekreference event.
Create a handler for that event.
Call toast inside the event.

### Link to public reproduction project repository

-

### Environment

```markdown
- .NET MAUI CommunityToolkit: latest (8.0)
- OS: Android (11+)
- .NET MAUI: .net 7
```

**Comment by pictos** [comment]
@FM1973 
Could you attach a small repro?

**Comment by VladislavAntonyuk** [comment]
The issue is not reproduced:
```csharp
public class TestPage : ContentPage
{
	public TestPage()
	{
		WeakReferenceMessenger.Default.Register<TestMessage>(this, async (r, m) =>
		{
			await Toast.Make(m.Value).Show();
		});

		WeakReferenceMessenger.Default.Send(new TestMessage("text"));
	}
}

public class TestMessage : ValueChangedMessage<string>
{
	public TestMessage(string text) : base(text)
	{
	}
}

**Comment by FM1973** [comment]
Thanks for your sample. This does work indeed.
Maybe thew problem is, that the source of my event is a background task.

{Java.Lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
   at Java.Interop.JniEnvironment.StaticMethods.CallStaticObjectMethod(JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 12890
   at Java.Interop.JniPeerMembers.JniStaticMethods.InvokeObjectMethod(String encodedMember, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:line 151
   at Android.Widget.Toast.MakeText(Context context, ICharSequence text, ToastLength duration) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Widget.Toast.cs:line 548
   at CommunityToolkit.Maui.Alerts.Toast.ShowPlatform(CancellationToken token) in /_/src/CommunityToolkit.Maui/Alerts/Toast/Toast.android.cs:line 48
   at CommunityToolkit.Maui.Alerts.Toast.Show(CancellationToken token) in /_/src/CommunityToolkit.Maui/Alerts/Toast/Toast.shared.cs:line 77
   at gehGassiApp.Services.DialogService.ToastAsync(String message, ToastDuration duration, Double fontSize) in D:\Kunden\GehGassi\gehGassiApp\gehGassiApp\Services\DialogService.cs:line 59
   at gehGassiApp.ViewModels.BaseViewModel.SystemMessageChanged() in D:\Kunden\GehGassi\gehGassiApp\gehGassiApp\ViewModels\BaseViewModel.cs:line 310
  --- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:167)
	at android.widget.Toast.getLooper(Toast.java:182)
	at android.widget.Toast.<init>(Toast.java:167)
	at android.widget.Toast.makeText(Toast.java:495)
	at android.widget.Toast.makeText(Toast.java:483)

  --- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:167)
	at android.widget.Toast.getLooper(Toast.java:182)
	at android.widget.Toast.<init>(Toast.java:167)
	at android.widget.Toast.makeText(Toast.java:495)
	at android.widget.Toast.makeText(Toast.java:483)
}

**Comment by FM1973** [comment]
Jup, when I call it on the main thread, everything works. Thanks!

**Comment by VladislavAntonyuk** [comment]
Toast is ui component, so it must be executed on ui thread: Can't toast on a thread that has not called Looper.prepare()
