### ISSUE TITLE
[BUG] StatusBar is not working for Blazor mobile

### ISSUE THREAD

**Issue by KSemenenko** [CommunityToolkit/Maui#880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you will add StatusBar to MainPage in Blazor mobile it will crashed on android.

### Expected Behavior

Not crashed =)

### Steps To Reproduce

1. Create new Blazor mobile project
2. Add StatusBar
3. Run on android

### Link to public reproduction project repository

No

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:
- .NET MAUI:
```

**Comment by KSemenenko** [comment]
Hi @brminnick of course

``` System.InvalidOperationException: Android Activity can't be null.
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo) in D:\a\_work\1\s\src\Controls\src\Xaml\ApplyPropertiesVisitor.cs:line 379
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ValueNode node, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\ApplyPropertiesVisitor.cs:line 62
   at Microsoft.Maui.Controls.Xaml.ValueNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 92
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 153
   at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 210
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 210
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 78
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 53
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 49
   at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[MainPage](MainPage view, Type callingType) in D:\a\_work\1\s\src\Controls\src\Xaml\ViewExtensions.cs:line 37
   at MauiApp1.MainPage.InitializeComponent() in /Users/ksemenenko/Developer/MauiApp1/MauiApp1/Microsoft.Maui.Controls.SourceGen/Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator/MainPage.xaml.sg.cs:line 26
   at MauiApp1.MainPage..ctor() in /Users/ksemenenko/Developer/MauiApp1/MauiApp1/MainPage.xaml.cs:line 7
   at MauiApp1.App..ctor() in /Users/ksemenenko/Developer/MauiApp1/MauiApp1/App.xaml.cs:line 9
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType) in D:\a\_work\1\s\src\Core\src\MauiContext.cs:line 68
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType) in D:\a\_work\1\s\src\Core\src\MauiContext.cs:line 68
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider provider)
   at Microsoft.Maui.MauiApplication.OnCreate() in D:\a\_work\1\s\src\Core\src\Platform\Android\MauiApplication.cs:line 37
   at Android.App.Application.n_OnCreate(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.App.Application.cs:line 1072
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
```

**Comment by KSemenenko** [comment]
[MauiApp1.zip](https://github.com/CommunityToolkit/Maui/files/10374076/MauiApp1.zip)

project

**Comment by pictos** [comment]
@KSemenenko can you upload it on GitHub and share the link? We don't download `zip` files

**Comment by KSemenenko** [comment]
<img width="929" alt="Screenshot 2023-01-09 at 21 25 35" src="https://user-images.githubusercontent.com/4385716/211401389-6218813b-2705-40d4-a7b8-2c2693e53bcb.png">
I think this is it. So probealy all of use use Shell, and in shell StatusBar works perfectly, but Maui blazor use just MainPage, and probably it's not initialized

**Comment by pictos** [comment]
@KSemenenko I would insist that you upload your sample to github or gitlab and share the link. We don't download zip files for security reasons. I'm not saying that you are a _bad guy_ and want to add something bad on that zip file, but if we open an exception for you, we've to open to others. You can find more info about our guidelines [here](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug).

Providing the reproduction will help us to focus just on the bug and not trying to replicate your scenario. I'm sorry for the inconvenience.

**Comment by KSemenenko** [comment]
Hi @pictos I totally get it, it's not good idea to download random zip files.

**Comment by Sokol2001** [comment]
Hi @pictos, here is an example 
https://github.com/Sokol2001/MauiApp

**Comment by VladislavAntonyuk** [comment]
@KSemenenko the link returns 404

**Comment by Sokol2001** [comment]
@VladislavAntonyuk, I'm sorry

Already fixed it, try again

**Comment by VladislavAntonyuk** [comment]
The issue is not reproduced: 
![image](https://user-images.githubusercontent.com/33021114/212348467-79375412-0d13-473b-bd5d-7298eaa9dbf9.png)

**Comment by VladislavAntonyuk** [comment]
hmm, seems like it doesn't crash only in Debug mode.

**Comment by KSemenenko** [comment]
It was fast 🚀
