### ISSUE TITLE
[BUG] StateContainer crash app when state change too fast 

### ISSUE THREAD

**Issue by Strypper** [CommunityToolkit/Maui#942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file.

### Current Behavior

I am currently testing the state container on WinUI and triggering the states by using windows size changed, I notice when I change the size slowly everything works perfectly but when I resize the windows which trigger the state jump between states too fast the app crash, I only tested it on Windows so I am don't whether this behavior is occurring on IOS or Android

### Expected Behavior

App not crash

### Steps To Reproduce

```cs
private void BasePage_SizeChanged(object sender, EventArgs e)
    {
        if (Window.Width < 500)
        {
            _vm.CurrentState = "Phone";
            return;
        }
        else if (Window.Width < 900)
        {
            _vm.CurrentState = "Tablet";
            return;
        }
        else if (Window.Width < 2000)
        {
            _vm.CurrentState = "Desktop";
            return;
        }
    }
```

```xml
 <ScrollView>
        <Grid
            toolkit:StateContainer.CanStateChange="{x:Binding CanStateChange}"
            toolkit:StateContainer.CurrentState="{x:Binding CurrentState}"
            toolkit:StateContainer.ShouldAnimateOnStateChange="True">
            <toolkit:StateContainer.StateViews>
                <app:ChatPagePhoneLayout toolkit:StateView.StateKey="Phone" />
                <app:ChatPageTabletLayout toolkit:StateView.StateKey="Tablet" />
                <app:ChatPageDesktopLayout toolkit:StateView.StateKey="Desktop" />
            </toolkit:StateContainer.StateViews>
        </Grid>
    </ScrollView>
```

```xml
<ContentView
    x:Class="MAUIsland.ChatPagePhoneLayout"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit">

    <ContentView.Resources>
        <x:Array x:Key="PropertyItemsSource" Type="{x:Type x:String}">
            <x:String>
                <![CDATA[
                                <strong style="color:blue">BorderColor</strong>, of type <strong style="color:blue">Color</strong>, describes the border color of the button.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">BorderWidth</strong>, of type <strong style="color:blue">double</strong>, defines the width of the button's border.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">CharacterSpacing</strong>, of type <strong style="color:blue">double</strong>, defines the spacing between characters of the button's text.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">Command</strong>, of type <strong style="color:blue">ICommand</strong>, defines the command that's executed when the button is tapped.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">CommandParameter</strong>, of type <strong style="color:blue">object</strong>, is the parameter that's passed to Command.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">ContentLayout</strong>, of type <strong style="color:blue">ButtonContentLayout</strong>, defines the object that controls the position of the button image and the spacing between the button's image and text.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">CornerRadius</strong>, of type <strong style="color:blue">int</strong>, describes the corner radius of the button's border.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">FontAttributes</strong>, of type <strong style="color:blue">FontAttributes</strong>, determines text style.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">FontAutoScalingEnabled</strong>, of type <strong style="color:blue">bool</strong>, defines whether the button text will reflect scaling preferences set in the operating system. The default value of this property is true.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">FontFamily</strong>, of type <strong style="color:blue">string</strong>, defines the font family.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">FontSize</strong>, of type <strong style="color:blue">double</strong>, defines the font size.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">ImageSource</strong>, of type <strong style="color:blue">ImageSource</strong>, specifies a bitmap image to display as the content of the button.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">LineBreakMode</strong>, of type <strong style="color:blue">LineBreakMode</strong>, determines how text should be handled when it can't fit on one line.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">Padding</strong>, of type <strong style="color:blue">Thickness</strong>, determines the button's padding.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">Text</strong>, of type <strong style="color:blue">string</strong>, defines the text displayed as the content of the button.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">TextColor</strong>, of type <strong style="color:blue">Color</strong>, describes the color of the button's text.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">TextTransform</strong>, of type <strong style="color:blue">TextTransform</strong>, defines the casing of the button's text.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">ImageSource</strong>, of type <strong style="color:blue">ImageSource</strong>, specifies a bitmap image to display as the content of the button.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">LineBreakMode</strong>, of type <strong style="color:blue">LineBreakMode</strong>, determines how text should be handled when it can't fit on one line.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">Padding</strong>, of type <strong style="color:blue">Thickness</strong>, determines the button's padding.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">Text</strong>, of type <strong style="color:blue">string</strong>, defines the text displayed as the content of the button.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">TextColor</strong>, of type <strong style="color:blue">Color</strong>, describes the color of the button's text.
                            ]]>
            </x:String>
            <x:String>
                <![CDATA[
                                <strong style="color:blue">TextTransform</strong>, of type <strong style="color:blue">TextTransform</strong>, defines the casing of the button's text.
                            ]]>
            </x:String>
        </x:Array>
    </ContentView.Resources>

    <VerticalStackLayout Spacing="10">
        <Frame Style="{x:StaticResource DocumentContentFrameStyle}">
            <CollectionView
                Footer="{x:StaticResource PropertiesListFooter}"
                Header="{x:StaticResource PropertiesListHeader}"
                ItemsSource="{x:StaticResource PropertyItemsSource}"
                Style="{x:StaticResource PropertiesListStyle}" />
        </Frame>
        <Editor HeightRequest="50" Placeholder="Enter message" />
    </VerticalStackLayout>
</ContentView>
```

### Link to public reproduction project repository

None

### Environment

```markdown
- .NET MAUI CommunityToolkit: 4.0
- OS: Window
- .NET MAUI: 7.0
```

**Comment by Strypper** [comment]
You guys need the source code ?

**Comment by brminnick** [comment]
Yes, please share a link to an open-source repository containing a working sample reproduction app. 

You can read more about it in the **Reporting A Bug** section of our contribution guide:

https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

**Comment by Strypper** [comment]
> 
https://github.com/Strypper/mauisland
Here is the link to the project, you don't need to dig inside the code to reproduce it I already did that for you 
Navigate to Chat using the flyout (Windows) 
Slowly resize windows from wide to narrow to change different states, if you resize the window too fast it will cause break

**Comment by Strypper** [comment]
Do you have any issue running the project ? @brminnick

**Comment by JingchengYang4** [comment]
This is true for iOS, MacCatalyst, and Android. One loading took less than 100ms to change and it crashed. The other took 2 seconds and worked.

`Unhandled managed exception: A task was canceled. (System.Threading.Tasks.TaskCanceledException)
     at CommunityToolkit.Maui.Layouts.StateContainerController.FadeLayoutChildren(Layout layout, Boolean shouldAnimate, Boolean isHidden, CancellationToken token) in /_/src/CommunityToolkit.Maui/Layouts/StateContainer/StateContainerController.shared.cs:line 146
     at CommunityToolkit.Maui.Layouts.StateContainerController.SwitchToState(String state, Boolean shouldAnimate, Nullable1 cancellationToken) in /_/src/CommunityToolkit.Maui/Layouts/StateContainer/StateContainerController.shared.cs:line 124
     at CommunityToolkit.Maui.Layouts.StateContainer.OnCurrentStateChanged(BindableObject bindable, Object oldValue, Object newValue) in /_/src/CommunityToolkit.Maui/Layouts/StateContainer/StateContainer.shared.cs:line 84
     at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle)
     at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
     at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)`

**Comment by VladislavAntonyuk** [comment]
I will take a look. Seems like we shouldn't throw Cancellation exception.

**Comment by brminnick** [comment]
StateContainer throws a StateContainerException when `CanStateChange` is `false` and the user attempts to change the state. 

Here is more information on how to use `CanStateChange` in our documentation: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/layouts/statecontainer#viewmodel

**Comment by VladislavAntonyuk** [comment]
hey @brminnick , how about `Unhandled managed exception: A task was canceled. (System.Threading.Tasks.TaskCanceledException) at CommunityToolkit.Maui.Layouts.StateContainerController.FadeLayoutChildren`?
I think we shouldn't be so aggressive in throwing exceptions.

**Comment by brminnick** [comment]
Hey Gang! We just opened a new Proposal on StateContainer + Unhandled Exceptions that I'd love for you to take a look at.

It is a breaking change, but I think it'll finally fix the headaches you've been having with StateContainer.

Leave a comment and let us know what you think! 

https://github.com/CommunityToolkit/Maui/issues/1027
